// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
// Lightweight per-item metadata (title + intro per language) for list pages
// and site search. Full item content is lazy-loaded in content.js.
// Regenerate with `npm run gen:content` (also runs on predev / prebuild).

export default {
  "Chalisa": {
    "ahoi-chalisa": {
      "titleHi": "अहोई चालीसा",
      "titleEn": "Ahoi Chalisa",
      "introHi": "अहोई चालीसा माता अहोई को समर्पित एक स्तुति है।",
      "introEn": "Shri Ahoi Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Ahoi"
    },
    "annapurna-chalisa": {
      "titleHi": "अन्नपूर्णा चालीसा",
      "titleEn": "Annapurna Chalisa",
      "introHi": "अन्नपूर्णा चालीसा माँ अन्नपूर्णा को समर्पित एक स्तुति है।",
      "introEn": "Shri Annapurna Chalisa - Hymn to Goddess Annapurna"
    },
    "balaji-chalisa": {
      "titleHi": "बालाजी चालीसा",
      "titleEn": "Bala ji Chalisa",
      "introHi": "बालाजी चालीसा भगवान बालाजी को समर्पित एक स्तुति है।",
      "introEn": "Shri Bala Ji Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Bala Ji"
    },
    "banglamukhi-chalisa": {
      "titleHi": "बांग्लामुखी चालीसा",
      "titleEn": "Maa Banglamukhi Chalisa",
      "introHi": "बगलामुखी चालीसा देवी बगलामुखी को समर्पित एक स्तुति है।",
      "introEn": "Shri Banglamukhi Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Banglamukhi"
    },
    "bhairav-chalisa": {
      "titleHi": "भैरव चालीसा",
      "titleEn": "Bhairav Chalisa",
      "introHi": "भैरव चालीसा भगवान भैरव को समर्पित एक स्तुति है।",
      "introEn": "Shri Bhairav Chalisa - Hymn to Lord Bhairav"
    },
    "brahma-chalisa": {
      "titleHi": "ब्रह्मा चालीसा",
      "titleEn": "Brahma Chalisa",
      "introHi": "ब्रह्मा चालीसा भगवान ब्रह्मा को समर्पित एक स्तुति है।",
      "introEn": "Shri Brahma Chalisa - Hymn to Lord Brahma"
    },
    "brahmacharini-chalisa": {
      "titleHi": "ब्रह्मचारिणी चालीसा",
      "titleEn": "Brahmacharini Chalisa",
      "introHi": "ब्रह्मचारिणी चालीसा माँ ब्रह्मचारिणी को समर्पित एक स्तुति है।",
      "introEn": "Shri Brahmacharini Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Brahmacharini"
    },
    "brihaspati-chalisa": {
      "titleHi": "बृहस्पति चालीसा",
      "titleEn": "Brihaspati Chalisa",
      "introHi": "बृहस्पति चालीसा बृहस्पति देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Brihaspati Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Brihaspati"
    },
    "budh-chalisa": {
      "titleHi": "बुद्ध चालीसा",
      "titleEn": "Budh Chalisa",
      "introHi": "बुध चालीसा बुध देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Budh Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Budh"
    },
    "chamunda-chalisa": {
      "titleHi": "चामुंडा चालीसा",
      "titleEn": "Chamumda Chalisa",
      "introHi": "चामुंडा चालीसा देवी चामुंडा को समर्पित एक स्तुति है।",
      "introEn": "Shri Chamunda Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Chamunda"
    },
    "chandra-chalisa": {
      "titleHi": "चंद्र चालीसा",
      "titleEn": "Chandra Chalisa",
      "introHi": "चंद्र चालीसा चंद्र देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Chandra Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Chandra"
    },
    "chandraghanta-chalisa": {
      "titleHi": "चंद्रघंटा चालीसा",
      "titleEn": "Chandraghanta Chalisa",
      "introHi": "चंद्रघंटा चालीसा माँ चंद्रघंटा को समर्पित एक स्तुति है।",
      "introEn": "Shri Chandraghanta Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Chandraghanta"
    },
    "chitragupta-chalisa": {
      "titleHi": "चित्रगुप्त चालीसा",
      "titleEn": "Chitragupta Chalisa",
      "introHi": "चित्रगुप्त चालीसा भगवान चित्रगुप्त को समर्पित एक स्तुति है।",
      "introEn": "Shri Chitragupta Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Chitragupta"
    },
    "durga-chalisa": {
      "titleHi": "दुर्गा चालीसा",
      "titleEn": "Durga Chalisa",
      "introHi": "दुर्गा चालीसा देवी दुर्गा को समर्पित एक स्तुति है। श्री दुर्गा चालीसा: संपूर्ण पाठ, अर्थ, विधि और लाभ",
      "introEn": "Durga Chalisa is a hymn honoring Goddess Durga"
    },
    "ganesh-chalisa": {
      "titleHi": "गणेश चालीसा",
      "titleEn": "Ganesh Chalisa",
      "introHi": "गणेश चालीसा विघ्नहर्ता भगवान गणेश को समर्पित है, जिनके स्मरण मात्र से सभी बाधाएँ दूर हो जाती हैं और कार्यों में सफलता मिलती है।",
      "introEn": "The Ganesh Chalisa is a powerful devotional hymn dedicated to Lord Ganesha, the remover of obstacles and the god of new beginnings."
    },
    "ganga-chalisa": {
      "titleHi": "गंगा माँ चालीसा",
      "titleEn": "Ganga Chalisa",
      "introHi": "गंगा चालीसा माँ गंगा को समर्पित एक स्तुति है।",
      "introEn": "Shri Ganga Chalisa - Hymn to Goddess Ganga"
    },
    "gayatri-chalisa": {
      "titleHi": "गायत्री चालीसा",
      "titleEn": "Gayatri Chalisa",
      "introHi": "गायत्री चालीसा माँ गायत्री को समर्पित एक स्तुति है",
      "introEn": "Shri Gayatri Chalisa - Hymn to Goddess Gayatri"
    },
    "guru-chalisa": {
      "titleHi": "गुरु चालीसा",
      "titleEn": "Guru Chalisa",
      "introHi": "गुरु चालीसा गुरुदेव को समर्पित एक स्तुति है।",
      "introEn": "Shri Guru Chalisa: Full Path, Meaning, and Benefits - Hymn to Guru"
    },
    "hanuman-chalisa": {
      "titleHi": "हनुमान चालीसा",
      "titleEn": "Hanuman Chalisa",
      "introHi": "यहाँ पढ़ें संपूर्ण श्री हनुमान चालीसा और हनुमान जी का आशीर्वाद पाएं।",
      "introEn": "Read the powerful Shri Hanuman Chalisa to remove obstacles and seek divine blessings"
    },
    "kalaratri-chalisa": {
      "titleHi": "कालरात्रि चालीसा",
      "titleEn": "Kalaratri Chalisa",
      "introHi": "कालरात्रि चालीसा माँ कालरात्रि को समर्पित एक स्तुति है।",
      "introEn": "Shri Kalaratri Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Kalaratri"
    },
    "kali-chalisa": {
      "titleHi": "काली माँ चालीसा",
      "titleEn": "Kali Chalisa",
      "introHi": "काली चालीसा माँ काली को समर्पित एक स्तुति है।",
      "introEn": "Shri Kali Chalisa - Hymn to Goddess Kali"
    },
    "kartikeya-chalisa": {
      "titleHi": "कार्तिकेय चालीसा",
      "titleEn": "Kartikeya Chalisa",
      "introHi": "कार्तिकेय चालीसा भगवान कार्तिकेय को समर्पित एक स्तुति है।\nEnglish - Shri Kartikeya Chal",
      "introEn": "Shri Kartikeya Chalisa - Hymn to Lord Kartikeya"
    },
    "katyayani-chalisa": {
      "titleHi": "कात्यायनी चालीसा",
      "titleEn": "Katyayani Chalisa",
      "introHi": "कात्यायनी चालीसा माँ कात्यायनी को समर्पित एक स्तुति है।",
      "introEn": "Shri Katyayani Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Katyayani"
    },
    "ketu-chalisa": {
      "titleHi": "केतु चालीसा",
      "titleEn": "Ketu Chalisa",
      "introHi": "केतु चालीसा केतु देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Ketu Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Ketu"
    },
    "khatu-shyam-chalisa": {
      "titleHi": "खाटू श्याम चालीसा",
      "titleEn": "Khatu shyam ji Chalisa",
      "introHi": "खाटू श्याम चालीसा बाबा खाटू श्याम को समर्पित एक स्तुति है।",
      "introEn": "Shri Khatu Shyam Chalisa - Hymn to Khatu Shyam"
    },
    "krishna-chalisa": {
      "titleHi": "कृष्णा चालीसा",
      "titleEn": "Krishna Chalisa",
      "introHi": "कृष्ण चालीसा भगवान कृष्ण को समर्पित एक स्तुति है",
      "introEn": "Shri Krishna Chalisa - Hymn to Lord Krishna"
    },
    "kuber-chalisa": {
      "titleHi": "कुबेर चालीसा",
      "titleEn": "Kuber Chalisa",
      "introHi": "कुबेर चालीसा भगवान कुबेर को समर्पित एक स्तुति है।",
      "introEn": "Shri Kuber Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Kuber"
    },
    "kushmanda-chalisa": {
      "titleHi": "कूष्मांडा चालीसा",
      "titleEn": "Kushmanda Chalisa",
      "introHi": "कुष्मांडा चालीसा माँ कुष्मांडा को समर्पित एक स्तुति है।",
      "introEn": "Shri Kushmanda Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Kushmanda"
    },
    "lakshmi-chalisa": {
      "titleHi": "लक्ष्मी चालीसा",
      "titleEn": "Lakshmi Chalisa",
      "introHi": "लक्ष्मी चालीसा माँ लक्ष्मी को समर्पित एक स्तुति है",
      "introEn": "Shri Lakshmi Chalisa - Hymn to Goddess Lakshmi"
    },
    "mahagauri-chalisa": {
      "titleHi": "महागौरी चालीसा",
      "titleEn": "Mahagauri Chalisa",
      "introHi": "महागौरी चालीसा माँ महागौरी को समर्पित एक स्तुति है।",
      "introEn": "Shri Mahagauri Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Mahagaur"
    },
    "mahakali-chalisa": {
      "titleHi": "महाकाली चालीसा",
      "titleEn": "Mahakali Chalisa",
      "introHi": "महाकाली चालीसा देवी महाकाली को समर्पित एक स्तुति है।",
      "introEn": "Shri Mahakali Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Mahakali"
    },
    "mangal-chalisa": {
      "titleHi": "मंगल चालीसा",
      "titleEn": "Mangal Chalisa",
      "introHi": "मंगल चालीसा मंगल देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Mangal Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Mangal"
    },
    "narmada-chalisa": {
      "titleHi": "नर्मदा चालीसा",
      "titleEn": "Narmada Chalisa",
      "introHi": "नर्मदा चालीसा माँ नर्मदा को समर्पित एक स्तुति है।",
      "introEn": "Shri Narmada Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Narmada"
    },
    "navgrah-chalisa": {
      "titleHi": "नवग्रह चालीसा",
      "titleEn": "Navgrah Chalisa",
      "introHi": "नवग्रह चालीसा नवग्रहों को समर्पित एक स्तुति है।",
      "introEn": "Shri Navgrah Chalisa: Full Path, Meaning, and Benefits - Hymn to Navgrah"
    },
    "parshuram-chalisa": {
      "titleHi": "श्री परशुराम चालीसा",
      "titleEn": "Parshuram ji Chalisa",
      "introHi": "परशुराम चालीसा भगवान परशुराम को समर्पित एक स्तुति है।",
      "introEn": "Shri Parshuram Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Parshuram"
    },
    "parvati-chalisa": {
      "titleHi": "पार्वती माँ चालीसा",
      "titleEn": "Parvati Chalisa",
      "introHi": "पार्वती चालीसा माँ पार्वती को समर्पित एक स्तुति है।",
      "introEn": "Shri Parvati Chalisa - Hymn to Goddess Parvati"
    },
    "radha-chalisa": {
      "titleHi": "राधा चालीसा",
      "titleEn": "Radha Chalisa",
      "introHi": "राधा चालीसा देवी राधा को समर्पित एक स्तुति है",
      "introEn": "Shri Radha Chalisa - Hymn to Goddess Radha"
    },
    "rahu-chalisa": {
      "titleHi": "राहु चालीसा",
      "titleEn": "Rahu Chalisa",
      "introHi": "राहु चालीसा राहु देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Rahu Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Rahu"
    },
    "ram-chalisa": {
      "titleHi": "राम चालीसा",
      "titleEn": "Ram Chalisa",
      "introHi": "श्री राम चालीसा: संपूर्ण पाठ, अर्थ, व्याख्या और विधि",
      "introEn": "Read the complete Shri Ram Chalisa to seek the divine blessings and righteous guidance of Lord Rama."
    },
    "ravidas-chalisa": {
      "titleHi": "रविदास चालीसा",
      "titleEn": "Ravidas ji Chalisa",
      "introHi": "रविदास चालीसा गुरु रविदास जी को समर्पित एक स्तुति है।",
      "introEn": "Shri Ravidas Chalisa: Full Path, Meaning, and Benefits - Hymn to Guru Ravidas"
    },
    "saibaba-chalisa": {
      "titleHi": "साईं बाबा चालीसा",
      "titleEn": "Sai baba ji Chalisa",
      "introHi": "साईं चालीसा साईं बाबा को समर्पित एक स्तुति है।",
      "introEn": "Shri Sai Chalisa - Hymn to Sai Baba"
    },
    "santoshi-chalisa": {
      "titleHi": "संतोषी माँ चालक",
      "titleEn": "Santoshi Chalisa",
      "introHi": "संतोषी चालीसा माँ संतोषी को समर्पित एक स्तुति है।",
      "introEn": "Shri Santoshi Chalisa - Hymn to Goddess Santoshi"
    },
    "saraswati-chalisa": {
      "titleHi": "सरस्वती चालीसा",
      "titleEn": "Saraswati Chalisa",
      "introHi": "सरस्वती चालीसा माँ सरस्वती को समर्पित एक स्तुति है",
      "introEn": "Shri Saraswati Chalisa - Hymn to Goddess Saraswati"
    },
    "shailaputri-chalisa": {
      "titleHi": "शैलपुत्री चालीसा",
      "titleEn": "Shailaputri Chalisa",
      "introHi": "शैलपुत्री चालीसा माँ शैलपुत्री को समर्पित एक स्तुति है।",
      "introEn": "Shri Shailaputri Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Shailaputri"
    },
    "shani-chalisa": {
      "titleHi": "शनि चालीसा",
      "titleEn": "Shani Chalisa",
      "introHi": "शनि चालीसा भगवान शनि को समर्पित एक स्तुति है। श्री शनि चालीसा: संपूर्ण पाठ, अर्थ, विधि और लाभ",
      "introEn": "Shri Shani Chalisa - Hymn to Lord Shani"
    },
    "sheetla-chalisa": {
      "titleHi": "शीतला चालीसा",
      "titleEn": "Sheetla Chalisa",
      "introHi": "शीतला चालीसा माँ शीतला को समर्पित एक स्तुति है।",
      "introEn": "Shri Sheetla Mata Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Sheetla Mata"
    },
    "shiv-chalisa": {
      "titleHi": "शिव चालीसा",
      "titleEn": "Shiv Chalisa",
      "introHi": "भगवान शिव की स्तुति",
      "introEn": "Read Shri Shiv Chalisa to seek Lord Shiva's blessings. Shri Shiv Chalisa - Hymn to Lord Shiva"
    },
    "shukra-chalisa": {
      "titleHi": "शुकर चालीसा",
      "titleEn": "Shukar Chalisa",
      "introHi": "शुक्र चालीसा शुक्र देव को समर्पित एक स्तुति है।",
      "introEn": "Shri Shukra Chalisa: Full Path, Meaning, and Benefits - Hymn to Lord Shukra"
    },
    "siddhidatri-chalisa": {
      "titleHi": "सिद्धिदात्री चालीसा",
      "titleEn": "Siddhidatri Chalisa",
      "introHi": "सिद्धिदात्री चालीसा माँ सिद्धिदात्री को समर्पित एक स्तुति है।",
      "introEn": "Shri Siddhidatri Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Siddhidatri"
    },
    "skandamata-chalisa": {
      "titleHi": "स्कंदमाता चालीसा",
      "titleEn": "Skandamata Chalisa",
      "introHi": "स्कंदमाता चालीसा माँ स्कंदमाता को समर्पित एक स्तुति है।",
      "introEn": "Shri Skandamata Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Skandamata"
    },
    "surya-chalisa": {
      "titleHi": "सूर्य चालीसा",
      "titleEn": "Surya Chalisa",
      "introHi": "सूर्य चालीसा भगवान सूर्य को समर्पित एक स्तुति है।",
      "introEn": "Shri Surya Chalisa - Hymn to Lord Surya"
    },
    "tuljabhavani-chalisa": {
      "titleHi": "तुलजा भवानी चालीसा",
      "titleEn": "Tulja Bhavani Chalisa",
      "introHi": "तुलजा भवानी चालीसा माता तुलजा भवानी को समर्पित एक स्तुति है।",
      "introEn": "Shri Tulja Bhavani Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Tulja Bhavani"
    },
    "tulsi-chalisa": {
      "titleHi": "तुलसी माँ चालीसा",
      "titleEn": "Tulsi Chalisa",
      "introHi": "तुलसी चालीसा माँ तुलसी को समर्पित एक स्तुति है।",
      "introEn": "Shri Tulsi Chalisa - Hymn to Goddess Tulsi"
    },
    "vindhyeshwari-chalisa": {
      "titleHi": "विन्ध्येश्वरी चालीसा",
      "titleEn": "Vindhyeshwari Chalisa",
      "introHi": "विन्ध्येश्वरी चालीसा देवी विन्ध्येश्वरी को समर्पित एक स्तुति है।",
      "introEn": "Shri Vindhyeshwari Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Vindhyeshwari"
    },
    "vishnu-chalisa": {
      "titleHi": "विष्णु चालीसा",
      "titleEn": "Vishnu Chalisa",
      "introHi": "विष्णु चालीसा भगवान विष्णु को समर्पित एक स्तुति है",
      "introEn": "Shri Vishnu Chalisa - Hymn to Lord Vishnu"
    },
    "yamuna-chalisa": {
      "titleHi": "यमुना चालीसा",
      "titleEn": "Maa Yamuna Chalisa",
      "introHi": "यमुना चालीसा माँ यमुना को समर्पित एक स्तुति है।",
      "introEn": "Shri Yamuna Chalisa: Full Path, Meaning, and Benefits - Hymn to Goddess Yamuna"
    }
  },
  "Mantras": {
    "aapadam-apahartaram-mantra": {
      "titleHi": "आपदां अपहर्तारं मंत्र",
      "titleEn": "Aapadam Apahartaram Mantra",
      "introHi": "यहाँ पढ़ें आपदां अपहर्तारं मंत्र हिंदी अर्थ सहित। सभी कष्टों और आपदाओं से मुक्ति पाने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Aapadam Apahartaram Mantra with meaning. Chant this mantra with devotion to find relief from all troubles and calamities."
    },
    "annapurna-mantra": {
      "titleHi": "अन्नपूर्णा मंत्र",
      "titleEn": "Maa Annapurna Mantra",
      "introHi": "यहाँ पढ़ें अन्नपूर्णा मंत्र हिंदी अर्थ सहित। माँ अन्नपूर्णा की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Annapurna Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Annapurna."
    },
    "dattatreya-mantra": {
      "titleHi": "दत्तात्रेय मंत्र",
      "titleEn": "Dattatreya Mantra",
      "introHi": "यहाँ पढ़ें दत्तात्रेय मंत्र हिंदी अर्थ सहित। भगवान दत्तात्रेय की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Dattatreya Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Dattatreya."
    },
    "devi-mantra": {
      "titleHi": "देवी मंत्र",
      "titleEn": "Devi Mantra",
      "introHi": "यहाँ पढ़ें देवी मंत्र हिंदी अर्थ सहित। माँ देवी की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Devi Mantra with meaning. Chant this mantra with devotion to receive the grace of Goddess Devi."
    },
    "durga-mantra": {
      "titleHi": "माँ दुर्गा मंत्र",
      "titleEn": "Durga mantra",
      "introHi": "यहाँ पढ़ें माँ दुर्गा मंत्र हिंदी अर्थ सहित। माँ दुर्गा की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Maa Durga Mantra with meaning. Chant this supreme mantra to receive the grace of Goddess Durga."
    },
    "ganesh-mantra": {
      "titleHi": "गणेश मंत्र",
      "titleEn": "Ganesh mantra",
      "introHi": "यहाँ पढ़ें गणेश मंत्र हिंदी अर्थ सहित। भगवान श्रीगणेश की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Ganesh Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Ganesh."
    },
    "gayatri-mantra": {
      "titleHi": "गायत्री मंत्र",
      "titleEn": "Gayatri Mantra",
      "introHi": "यहाँ पढ़ें गायत्री मंत्र हिंदी अर्थ सहित। बुद्धि, ज्ञान और तेज की प्राप्ति के लिए इस महामंत्र का जाप करें।",
      "introEn": "Read the sacred Gayatri Mantra with meaning. Chant this supreme mantra for wisdom, knowledge and inner radiance."
    },
    "guru-mantra": {
      "titleHi": "गुरु मंत्र",
      "titleEn": "Guru Mantra",
      "introHi": "यहाँ पढ़ें गुरु मंत्र हिंदी अर्थ सहित। गुरु का आशीर्वाद प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Guru Mantra with meaning. Chant this mantra with devotion to receive the blessings of the Guru."
    },
    "hanuman-mantra": {
      "titleHi": "हनुमान मंत्र",
      "titleEn": "Hanuman Mantra",
      "introHi": "यहाँ पढ़ें हनुमान मंत्र हिंदी अर्थ सहित। भगवान श्रीहनुमान की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Hanuman Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Hanuman."
    },
    "hare-krishna-mahamantra": {
      "titleHi": "हरे कृष्ण महामंत्र",
      "titleEn": "Hare Krishna mantra",
      "introHi": "यहाँ पढ़ें हरे कृष्ण महामंत्र हिंदी अर्थ सहित। भगवान श्रीकृष्ण की कृपा प्राप्त करने के लिए इस महामंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Hare Krishna Mahamantra with meaning. Chant this Mahamantra with devotion to receive the grace of Lord Krishna."
    },
    "kaal-bhairav-mantra": {
      "titleHi": "काल भैरव मंत्र",
      "titleEn": "Kaal Bhairav Mantra",
      "introHi": "यहाँ पढ़ें काल भैरव मंत्र हिंदी अर्थ सहित। भगवान काल भैरव की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Kaal Bhairav Mantra with meaning. Chant this mantra with devotion to receive the grace of Lord Kaal Bhairav."
    },
    "kali-mantra": {
      "titleHi": "काली मंत्र",
      "titleEn": "Maa Kali Mantra",
      "introHi": "यहाँ पढ़ें काली मंत्र हिंदी अर्थ सहित। माँ काली की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Kali Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Kali."
    },
    "ketu-mantra": {
      "titleHi": "केतु मंत्र",
      "titleEn": "Ketu mantra",
      "introHi": "यहाँ पढ़ें केतु मंत्र हिंदी अर्थ सहित। केतुदेव की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Ketu Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Ketu."
    },
    "kuber-mantra": {
      "titleHi": "कुबेर मंत्र",
      "titleEn": "Kuber Mantra",
      "introHi": "यहाँ पढ़ें कुबेर मंत्र हिंदी अर्थ सहित। भगवान कुबेर की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Kuber Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Kuber."
    },
    "maa-brahmacharini-mantra": {
      "titleHi": "माँ ब्रह्मचारिणी मंत्र",
      "titleEn": "Maa Brahmacharini Mantra",
      "introHi": "यहाँ पढ़ें माँ ब्रह्मचारिणी मंत्र हिंदी अर्थ सहित। माँ ब्रह्मचारिणी की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Brahmacharini Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Brahmacharini."
    },
    "maa-chandraghanta-mantra": {
      "titleHi": "माँ चंद्रघंटा मंत्र",
      "titleEn": "Maa Chandraghanta Mantra",
      "introHi": "यहाँ पढ़ें माँ चंद्रघंटा मंत्र हिंदी अर्थ सहित। माँ चंद्रघंटा की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Chandraghanta Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Chandraghanta."
    },
    "maa-kalratri-mantra": {
      "titleHi": "माँ कालरात्रि मंत्र",
      "titleEn": "Maa Kalaratri Mantra",
      "introHi": "यहाँ पढ़ें माँ कालरात्रि मंत्र हिंदी अर्थ सहित। माँ कालरात्रि की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Kalaratri Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Kalaratri."
    },
    "maa-katyayani-mantra": {
      "titleHi": "माँ कात्यायनी मंत्र",
      "titleEn": "Maa katyayani mantra",
      "introHi": "यहाँ पढ़ें माँ कात्यायनी मंत्र हिंदी अर्थ सहित। माँ कात्यायनी की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Katyayani Mantra with its English meaning. Chant it with devotion to receive the blessings of Goddess Katyayani."
    },
    "maa-kushmanda-mantra": {
      "titleHi": "माँ कुष्मांडा मंत्र",
      "titleEn": "Maa Kushmanda Mantra",
      "introHi": "यहाँ पढ़ें माँ कुष्मांडा मंत्र हिंदी अर्थ सहित। माँ कुष्मांडा की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Kushmanda Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Kushmanda."
    },
    "maa-mahagauri-mantra": {
      "titleHi": "माँ महागौरी मंत्र",
      "titleEn": "Maa Mahagauri Mantra",
      "introHi": "यहाँ पढ़ें माँ महागौरी मंत्र हिंदी अर्थ सहित। माँ महागौरी की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Mahagauri Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Mahagauri."
    },
    "maa-shailputri-mantra": {
      "titleHi": "माँ शैलपुत्री मंत्र",
      "titleEn": "Maa Shailputri Mantra",
      "introHi": "यहाँ पढ़ें माँ शैलपुत्री मंत्र हिंदी अर्थ सहित। माँ शैलपुत्री की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Shailputri Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Shailputri."
    },
    "maa-siddhidatri-mantra": {
      "titleHi": "माँ सिद्धिदात्री मंत्र",
      "titleEn": "Maa Siddhidatri Mantra",
      "introHi": "यहाँ पढ़ें माँ सिद्धिदात्री मंत्र हिंदी अर्थ सहित। माँ सिद्धिदात्री की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Siddhidatri Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Siddhidatri."
    },
    "maa-skandamata-mantra": {
      "titleHi": "माँ स्कंदमाता मंत्र",
      "titleEn": "Maa Skandamata Mantra",
      "introHi": "यहाँ पढ़ें माँ स्कंदमाता मंत्र हिंदी अर्थ सहित। माँ स्कंदमाता की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Maa Skandamata Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Skandamata."
    },
    "mahalakshmi-mantra": {
      "titleHi": "महालक्ष्मी मंत्र",
      "titleEn": "Mahalakshmi Mantra",
      "introHi": "यहाँ पढ़ें महालक्ष्मी मंत्र हिंदी अर्थ सहित। माता महालक्ष्मी की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Mahalakshmi Mantra with meaning. Chant this supreme mantra to receive the grace of Goddess Mahalakshmi."
    },
    "mahamrityunjaya-mantra": {
      "titleHi": "महामृत्युंजय मंत्र",
      "titleEn": "Mahamrityunjaya Mantra",
      "introHi": "यहाँ पढ़ें महामृत्युंजय मंत्र हिंदी अर्थ सहित। रोग, भय और अकाल मृत्यु से रक्षा के लिए भगवान शिव के इस महामंत्र का जाप करें।",
      "introEn": "Read the Mahamrityunjaya Mantra with meaning. Chant this great mantra of Lord Shiva for protection from illness, fear and untimely death."
    },
    "narasimha-mantra": {
      "titleHi": "नरसिंह मंत्र",
      "titleEn": "Narasimha Mantra",
      "introHi": "यहाँ पढ़ें नरसिंह मंत्र हिंदी अर्थ सहित। भगवान श्रीनरसिंह की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Narasimha Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Narasimha."
    },
    "narayana-mantra": {
      "titleHi": "नारायण मंत्र",
      "titleEn": "Narayana Mantra",
      "introHi": "यहाँ पढ़ें नारायण मंत्र हिंदी अर्थ सहित। भगवान श्रीनारायण की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Narayana Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Narayana."
    },
    "navgrah-mantra": {
      "titleHi": "नवग्रह मंत्र",
      "titleEn": "Navgrah Mantra",
      "introHi": "यहाँ पढ़ें नवग्रह मंत्र हिंदी अर्थ सहित। नवग्रहों की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Navgrah Mantra with meaning. Chant this supreme mantra to receive the grace of the Navgrah."
    },
    "purnamadah-mantra": {
      "titleHi": "पूर्णमदः मंत्र",
      "titleEn": "Purnamadah Mantra",
      "introHi": "यहाँ पढ़ें पूर्णमदः मंत्र हिंदी अर्थ सहित। ईश्वरीय पूर्णता का अनुभव करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Purnamadah Mantra with meaning. Chant this mantra with devotion to experience divine completeness."
    },
    "radha-krishna-mantra": {
      "titleHi": "राधा कृष्ण मंत्र",
      "titleEn": "Radha Krishna Mantra",
      "introHi": "यहाँ पढ़ें राधा कृष्ण मंत्र हिंदी अर्थ सहित। श्री राधा-कृष्ण की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Radha Krishna Mantra with meaning. Chant this supreme mantra to receive the grace of Radha Krishna."
    },
    "rahu-mantra": {
      "titleHi": "राहु मंत्र",
      "titleEn": "Rahu Mantra",
      "introHi": "यहाँ पढ़ें राहु मंत्र हिंदी अर्थ सहित। राहुदेव की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Rahu Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Rahu."
    },
    "ram-mantra": {
      "titleHi": "श्री राम मंत्र",
      "titleEn": "Shri Ram Mantra",
      "introHi": "यहाँ पढ़ें राम मंत्र हिंदी अर्थ सहित। भगवान श्रीराम की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Ram Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Ram."
    },
    "saraswati-mantra": {
      "titleHi": "सरस्वती मंत्र",
      "titleEn": "Saraswati Mantra",
      "introHi": "यहाँ पढ़ें सरस्वती मंत्र हिंदी अर्थ सहित। माँ सरस्वती की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Saraswati Mantra with meaning. Chant this supreme mantra to receive the grace of Goddess Saraswati."
    },
    "sarva-mangal-mangalye-mantra": {
      "titleHi": "सर्वमंगलमांगल्ये मंत्र",
      "titleEn": "Sarva Mangal Mangalye Mantra",
      "introHi": "सर्वमंगलमांगल्ये मंत्र – हिंदी अर्थ, लाभ, जाप विधि और महत्व",
      "introEn": "Sarva Mangal Mangalye Mantra – Meaning, Benefits, Chanting Method & Significance"
    },
    "shani-dev-mantra": {
      "titleHi": "शनि देव मंत्र",
      "titleEn": "Shani Dev Mantra",
      "introHi": "यहाँ पढ़ें शनि देव मंत्र हिंदी अर्थ सहित। भगवान शनिदेव की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Shani Dev Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Shani Dev."
    },
    "shanti-mantra": {
      "titleHi": "शांति मंत्र",
      "titleEn": "Shanti Mantra",
      "introHi": "यहाँ पढ़ें शांति मंत्र हिंदी अर्थ सहित। मन की शांति प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Shanti Mantra with meaning. Chant this mantra with devotion to receive peace of mind."
    },
    "shiv-mantra": {
      "titleHi": "शिव मंत्र",
      "titleEn": "Shiv mantra",
      "introHi": "यहाँ पढ़ें ॐ नमः शिवाय पंचाक्षर मंत्र हिंदी अर्थ सहित। भगवान शिव की कृपा पाने के लिए इस महामंत्र का जाप करें।",
      "introEn": "Read the (Shiv mantra) Om Namah Shivaya Panchakshara Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Shiva."
    },
    "surya-mantra": {
      "titleHi": "सूर्य मंत्र",
      "titleEn": "Surya Mantra",
      "introHi": "यहाँ पढ़ें सूर्य मंत्र हिंदी अर्थ सहित। भगवान सूर्यदेव की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Surya Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Surya."
    },
    "tulsi-mantra": {
      "titleHi": "तुलसी मंत्र",
      "titleEn": "Maa Tulsi Mantra",
      "introHi": "यहाँ पढ़ें तुलसी मंत्र हिंदी अर्थ सहित। माता तुलसी की कृपा प्राप्त करने के लिए इस मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Read the Tulsi Mantra with meaning. Chant this mantra with devotion to receive the grace of Mother Tulsi."
    },
    "vishnu-mantra": {
      "titleHi": "विष्णु मंत्र",
      "titleEn": "Vishnu mantra",
      "introHi": "यहाँ पढ़ें विष्णु मंत्र हिंदी अर्थ सहित। भगवान श्रीविष्णु की कृपा प्राप्त करने के लिए इस पवित्र मंत्र का श्रद्धापूर्वक जाप करें।",
      "introEn": "Vishnu Mantra with meaning. Chant this supreme mantra to receive the grace of Lord Vishnu."
    }
  },
  "Aartis": {
    "ambe-mata-ki-aarti": {
      "titleHi": "श्री अम्बे माता की आरती",
      "titleEn": "Shri Ambe Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री अम्बे माता की आरती हिंदी में और माँ अम्बे की कृपा प्राप्त करें।",
      "introEn": "Read Shri Ambe Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Ambe."
    },
    "annapurna-mata-ji-ki-aarti": {
      "titleHi": "श्री अन्नपूर्णा माता जी की आरती",
      "titleEn": "Shri Annapurna Mata Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री अन्नपूर्णा माता जी की आरती हिंदी में और माँ अन्नपूर्णा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Annapurna Mata Ji Ki Aarti in Hindi and seek the divine blessings of Goddess Annapurna."
    },
    "baglamukhi-mata-ki-aarti": {
      "titleHi": "श्री बगलामुखी माता की आरती",
      "titleEn": "Shri Baglamukhi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री बगलामुखी माता की आरती हिंदी में और माँ बगलामुखी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Baglamukhi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Baglamukhi."
    },
    "banke-bihari-ji-ki-aarti": {
      "titleHi": "श्री बांके बिहारी जी की आरती",
      "titleEn": "Shri Banke Bihari Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री बांके बिहारी जी की आरती हिंदी में और भगवान बांके बिहारी जी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Banke Bihari Ji Ki Aarti in Hindi and seek the divine blessings of Lord Banke Bihari Ji."
    },
    "bhairav-baba-ki-aarti": {
      "titleHi": "श्री भैरव बाबा की आरती",
      "titleEn": "Shri Bhairav Baba Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री भैरव बाबा  की आरती हिंदी में और श्री भैरव बाबा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Bhairav Baba Ki Aarti in Hindi and seek the divine blessings of Shri Bhairav Baba."
    },
    "brahmacharini-mata-ki-aarti": {
      "titleHi": "श्री ब्रह्मचारिणी माता की आरती",
      "titleEn": "Shri Brahmacharini Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री ब्रह्मचारिणी माता की आरती हिंदी में और माँ ब्रह्मचारिणी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Brahmacharini Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Brahmacharini."
    },
    "chandraghanta-mata-ki-aarti": {
      "titleHi": "श्री चंद्रघंटा माता की आरती",
      "titleEn": "Shri Chandraghanta Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री चंद्रघंटा माता की आरती हिंदी में और माँ चंद्रघंटा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Chandraghanta Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Chandraghanta."
    },
    "chintpurni-mata-ki-aarti": {
      "titleHi": "श्री चिंतपूर्णी माता की आरती",
      "titleEn": "Shri Chintpurni Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री चिंतपूर्णी माता की आरती हिंदी में और माँ चिंतपूर्णी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Chintpurni Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Chintpurni."
    },
    "durga-mata-ki-aarti": {
      "titleHi": "श्री दुर्गा माता की आरती",
      "titleEn": "Shri Durga Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री दुर्गा माता की आरती हिंदी में और माँ दुर्गा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Durga Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Durga."
    },
    "ganesh-ji-ki-aarti": {
      "titleHi": "श्री गणेश जी की आरती",
      "titleEn": "Shri Ganesh ji ki aarti",
      "introHi": "यहाँ पढ़ें श्री गणेश जी की आरती हिंदी में और भगवान गणेश की कृपा प्राप्त करें।",
      "introEn": "Read Shri Ganesh Ji Ki Aarti in Hindi and seek the divine blessings of Lord Ganesha."
    },
    "gange-mata-ki-aarti": {
      "titleHi": "श्री गंगे माता की आरती",
      "titleEn": "Shri Gange Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री गंगे माता की आरती हिंदी में और माँ गंगा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Gange Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Ganga."
    },
    "gayatri-mata-ki-aarti": {
      "titleHi": "श्री गायत्री माता की आरती",
      "titleEn": "Shri Gayatri Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री गायत्री माता की आरती हिंदी में और माँ गायत्री की कृपा प्राप्त करें।",
      "introEn": "Read Shri Gayatri Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Gayatri."
    },
    "hanuman-ji-ki-aarti": {
      "titleHi": "श्री हनुमान जी की आरती",
      "titleEn": "Shri Hanuman Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री हनुमान जी की आरती हिंदी में और भगवान हनुमान की कृपा प्राप्त करें।",
      "introEn": "Read Shri Hanuman Ji Ki Aarti in Hindi and seek the divine blessings of Lord Hanuman."
    },
    "jagannath-ji-ki-aarti": {
      "titleHi": "श्री जगन्नाथ जी की आरती",
      "titleEn": "Shri Jagannath Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री जगन्नाथ जी की आरती हिंदी में और भगवान जगन्नाथ जी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Jagannath Ji Ki Aarti in Hindi and seek the divine blessings of Lord Jagannath Ji."
    },
    "kaalratri-mata-ki-aarti": {
      "titleHi": "श्री कालरात्रि माता की आरती",
      "titleEn": "Shri Kaalratri Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री कालरात्रि माता की आरती हिंदी में और माँ कालरात्रि की कृपा प्राप्त करें।",
      "introEn": "Read Shri Kaalratri Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Kaalratri."
    },
    "kamakhya-mata-ki-aarti": {
      "titleHi": "श्री कामाख्या माता की आरती",
      "titleEn": "Shri Kamakhya Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री कामाख्या माता की आरती हिंदी में और माँ कामाख्या की कृपा प्राप्त करें।",
      "introEn": "Read Shri Kamakhya Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Kamakhya."
    },
    "karni-mata-ki-aarti": {
      "titleHi": "श्री करणी माता की आरती",
      "titleEn": "Shri Karni Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री करणी माता की आरती हिंदी में और माँ करणी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Karni Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Karni."
    },
    "katyayani-mata-ki-aarti": {
      "titleHi": "श्री कात्यायनी माता की आरती",
      "titleEn": "Shri Katyayani Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री कात्यायनी माता की आरती हिंदी में और माँ कात्यायनी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Katyayani Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Katyayani."
    },
    "khatu-shyam-ji-ki-aarti": {
      "titleHi": "श्री खाटू श्याम जी की आरती",
      "titleEn": "Shri Khatu Shyam Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री खाटू श्याम जी की आरती हिंदी में और भगवान खाटू श्याम जी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Khatu Shyam Ji Ki Aarti in Hindi and seek the divine blessings of Lord Khatu Shyam Ji."
    },
    "kushmanda-mata-ki-aarti": {
      "titleHi": "श्री कूष्मांडा माता की आरती",
      "titleEn": "Shri Kushmanda Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री कूष्मांडा माता की आरती हिंदी में और माँ कूष्मांडा की कृपा प्राप्त करें।",
      "introEn": "Read Shri Kushmanda Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Kushmanda."
    },
    "mahagauri-mata-ki-aarti": {
      "titleHi": "श्री महागौरी माता की आरती",
      "titleEn": "Shri Mahagauri Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री महागौरी माता की आरती हिंदी में और माँ महागौरी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Mahagauri Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Mahagauri."
    },
    "naina-devi-mata-ki-aarti": {
      "titleHi": "श्री नैना देवी माता की आरती",
      "titleEn": "Shri Naina Devi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री नैना देवी माता की आरती हिंदी में और माँ नैना देवी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Naina Devi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Naina Devi.\n\n────────"
    },
    "navgrah-aarti": {
      "titleHi": "श्री नवग्रह आरती",
      "titleEn": "Shri Navgrah Aarti",
      "introHi": "यहाँ पढ़ें श्री नवग्रह आरती हिंदी में और नवग्रहों की कृपा प्राप्त करें।",
      "introEn": "Read Shri Navgrah Aarti in Hindi and seek the divine blessings of the Navgrahas."
    },
    "radha-rani-ji-ki-aarti": {
      "titleHi": "श्री राधारानी जी की आरती",
      "titleEn": "Shri Radha Rani Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री राधारानी जी की आरती हिंदी में और श्री राधारानी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Radha Rani Ji Ki Aarti in Hindi and seek the divine blessings of Shri Radha Rani."
    },
    "sai-baba-ki-aarti": {
      "titleHi": "साईं बाबा जी की आरती",
      "titleEn": "Sai baba ji ki  Aarti",
      "introHi": "साईं बाबा जी की आरती का पाठ करें और  साईं बाबा जी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Sai Baba Ki Aarti and seek the divine blessings of Shri Sai Baba."
    },
    "salasar-balaji-ki-aarti": {
      "titleHi": "श्री सालासर बालाजी की आरती",
      "titleEn": "Shri Salasar Balaji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री सालासर बालाजी की आरती हिंदी में और श्री सालासर बालाजी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Salasar Balaji Ki Aarti in Hindi and seek the divine blessings of Shri Salasar Balaji."
    },
    "santoshi-mata-ki-aarti": {
      "titleHi": "श्री संतोषी माता की आरती",
      "titleEn": "Shri Santoshi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री संतोषी माता की आरती हिंदी में और माँ संतोषी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Santoshi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Santoshi."
    },
    "satyanarayan-bhagwan-ki-aarti": {
      "titleHi": "श्री सत्यनारायण भगवान की आरती",
      "titleEn": "Shri Satyanarayan Bhagwan Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री सत्यनारायण भगवान की आरती हिंदी में और भगवान सत्यनारायण की कृपा प्राप्त करें।",
      "introEn": "Read Shri Satyanarayan Bhagwan Ki Aarti in Hindi and seek the divine blessings of Lord Satyanarayan."
    },
    "shailputri-mata-ki-aarti": {
      "titleHi": "श्री शैलपुत्री माता की आरती",
      "titleEn": "Shri Shailputri Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री शैलपुत्री माता की आरती हिंदी में और माँ शैलपुत्री की कृपा प्राप्त करें।",
      "introEn": "Read Shri Shailputri Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Shailputri."
    },
    "shiv-ji-ki-aarti": {
      "titleHi": "श्री शिव जी की आरती",
      "titleEn": "Shri Shiv ji ki aarti",
      "introHi": "यहाँ पढ़ें श्री शिव जी की आरती हिंदी में और भगवान शिव की कृपा प्राप्त करें।",
      "introEn": "Read Shiv Ji Ki Aarti in Hindi and seek the divine blessings of Lord Shiva."
    },
    "shri-krishna-ji-ki-aarti": {
      "titleHi": "श्री कृष्ण जी की आरती",
      "titleEn": "Shri Krishna Ji Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री कृष्ण जी की आरती हिंदी में और भगवान श्रीकृष्ण की कृपा प्राप्त करें।",
      "introEn": "Read Shri Krishna Ji Ki Aarti in Hindi and seek the divine blessings of Lord Krishna."
    },
    "shri-lakshmi-mata-ki-aarti": {
      "titleHi": "श्री लक्ष्मी माता की आरती",
      "titleEn": "Shri Lakshmi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री लक्ष्मी माता की आरती हिंदी में और माँ लक्ष्मी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Lakshmi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Lakshmi."
    },
    "shri-saraswati-mata-ki-aarti": {
      "titleHi": "श्री सरस्वती माता की आरती",
      "titleEn": "Shri Saraswati Mata Ki Aarti",
      "introHi": "श्री सरस्वती माता की आरती का पाठ करें और माता सरस्वती की कृपा प्राप्त करें।",
      "introEn": "Read Shri Saraswati Mata Ki Aarti and seek the divine blessings of Goddess Saraswati."
    },
    "shri-shani-dev-ki-aarti": {
      "titleHi": "श्री शनि देव जी की आरती",
      "titleEn": "Shri Shani dev ji  Ki Aarti",
      "introHi": "श्री शनि देव जी की आरती का पाठ करें और श्री शनि देव जी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Shani Dev Ji Ki Aarti and seek the divine blessings of Shri Shani Dev Ji."
    },
    "shri-vishnu-bhagwan-ki-aarti": {
      "titleHi": "श्री विष्णु भगवान की आरती",
      "titleEn": "Shri Vishnu Bhagwan Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री विष्णु भगवान की आरती हिंदी में और भगवान विष्णु की कृपा प्राप्त करें।",
      "introEn": "Read Shri Vishnu Bhagwan Ki Aarti in Hindi and seek the divine blessings of Lord Vishnu."
    },
    "siddhidatri-mata-ki-aarti": {
      "titleHi": "श्री सिद्धिदात्री माता की आरती",
      "titleEn": "Shri Siddhidatri Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री सिद्धिदात्री माता की आरती हिंदी में और माँ सिद्धिदात्री की कृपा प्राप्त करें।",
      "introEn": "Read Shri Siddhidatri Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Siddhidatri."
    },
    "skandamata-ki-aarti": {
      "titleHi": "श्री स्कंदमाता की आरती",
      "titleEn": "Shri Skandamata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री स्कंदमाता की आरती हिंदी में और माँ स्कंदमाता की कृपा प्राप्त करें।",
      "introEn": "Read Shri Skandamata Ki Aarti in Hindi and seek the divine blessings of Goddess Skandamata."
    },
    "surya-dev-ki-aarti": {
      "titleHi": "श्री सूर्य देव की आरती",
      "titleEn": "Shri Surya Dev Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री सूर्य देव की आरती हिंदी में और भगवान सूर्य देव की कृपा प्राप्त करें।",
      "introEn": "Read Shri Surya Dev Ki Aarti in Hindi and seek the divine blessings of Lord Surya Dev."
    },
    "tulsi-mata-ki-aarti": {
      "titleHi": "श्री तुलसी माता की आरती",
      "titleEn": "Shri Tulsi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री तुलसी माता की आरती हिंदी में और माँ तुलसी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Tulsi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Tulsi."
    },
    "vaishnavi-mata-ki-aarti": {
      "titleHi": "श्री वैष्णवी माता की आरती",
      "titleEn": "Shri Vaishnavi Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री वैष्णवी माता की आरती हिंदी में और माँ वैष्णवी की कृपा प्राप्त करें।",
      "introEn": "Read Shri Vaishnavi Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Vaishnavi."
    },
    "yamuna-mata-ki-aarti": {
      "titleHi": "श्री यमुना माता की आरती",
      "titleEn": "Shri Yamuna Mata Ki Aarti",
      "introHi": "यहाँ पढ़ें श्री यमुना माता की आरती हिंदी में और माँ यमुना की कृपा प्राप्त करें।",
      "introEn": "Read Shri Yamuna Mata Ki Aarti in Hindi and seek the divine blessings of Goddess Yamuna."
    }
  },
  "Stotras": {
    "aditya-hridaya-stotram": {
      "titleHi": "श्री आदित्य हृदय स्तोत्रम्",
      "titleEn": "Aditya Hridaya Stotram",
      "introHi": "यहाँ पढ़ें श्री आदित्य हृदय स्तोत्रम् हिंदी अर्थ सहित। सूर्यदेव की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Aditya Hridaya Stotram with Hindi meaning. Chant this sacred hymn to seek the blessings of Lord Surya."
    },
    "bajrang-baan": {
      "titleHi": "बजरंग बाण",
      "titleEn": "Bajrang Baan",
      "introHi": "यहाँ पढ़ें बजरंग बाण हिंदी अर्थ सहित। भगवान हनुमान की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Bajrang Baan with Hindi meaning. Recite this sacred prayer to seek the blessings of Lord Hanuman."
    },
    "devi-mahatmya-stotra": {
      "titleHi": "देवी महात्म्य स्तोत्र",
      "titleEn": "Devi Mahatmya Stotra",
      "introHi": "देवी महात्म्य स्तोत्र देवी की शक्ति और महिमा का वर्णन करने वाला एक पवित्र स्तोत्र है, जिसका पाठ सुरक्षा और आशीर्वाद के लिए किया जाता है।",
      "introEn": "A sacred hymn praising the divine energy and power of the Divine Mother, recited for protection and blessings."
    },
    "ganapati-atharvashirsha": {
      "titleHi": "श्री गणपति अथर्वशीर्ष",
      "titleEn": "Shri Ganapati Atharvashirsha",
      "introHi": "यहाँ पढ़ें श्री गणपति अथर्वशीर्ष हिंदी अर्थ सहित। भगवान गणेश की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Ganapati Atharvashirsha with Hindi meaning. Chant to seek the divine blessings of Lord Ganesha."
    },
    "kanakadhara-stotram": {
      "titleHi": "श्री कनकधारा स्तोत्रम्",
      "titleEn": "Kanakadhara Stotram",
      "introHi": "यहाँ पढ़ें श्री कनकधारा स्तोत्रम् हिंदी अर्थ सहित। माता लक्ष्मी की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Kanakadhara Stotram with Hindi meaning. Chant to receive the divine blessings of Goddess Lakshmi."
    },
    "lakshmi-stotra": {
      "titleHi": "लक्ष्मी स्तोत्र",
      "titleEn": "Lakshmi Stotra",
      "introHi": "लक्ष्मी स्तोत्र देवी लक्ष्मी को समर्पित एक दिव्य स्तोत्र है, जिसका पाठ समृद्धि और आशीर्वाद के लिए किया जाता है।",
      "introEn": "A divine hymn dedicated to Goddess Lakshmi, the goddess of prosperity and wealth, recited for abundance and blessings."
    },
    "lalita-sahasranama-stotram": {
      "titleHi": "श्री ललिता सहस्रनाम स्तोत्रम्",
      "titleEn": "Shri Lalita Sahasranama Stotram",
      "introHi": "यहाँ पढ़ें श्री ललिता सहस्रनाम स्तोत्रम् हिंदी अर्थ सहित। माता ललिता की कृपा प्राप्त करने के लिए इसका पाठ करें।",
      "introEn": "Read Shri Lalita Sahasranama Stotram with Hindi meaning. Chant to receive the divine blessings of Goddess Lalita."
    },
    "narayana-kavacham": {
      "titleHi": "श्री नारायण कवचम्",
      "titleEn": "Narayana Kavacham",
      "introHi": "यहाँ पढ़ें श्री नारायण कवचम् हिंदी अर्थ सहित। भगवान विष्णु की कृपा और रक्षा प्राप्त करने के लिए इसका पाठ करें।",
      "introEn": "Read Narayana Kavacham with Hindi meaning. Chant this sacred hymn to receive Lord Vishnu’s protection and blessings."
    },
    "rama-raksha-stotram": {
      "titleHi": "श्री राम रक्षा स्तोत्रम्",
      "titleEn": "Rama Raksha Stotram",
      "introHi": "यहाँ पढ़ें श्री राम रक्षा स्तोत्रम् हिंदी अर्थ सहित। भगवान श्रीराम की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Rama Raksha Stotram with Hindi meaning. Chant this sacred hymn to seek the blessings of Lord Rama."
    },
    "sankatmochan-hanuman-ashtak": {
      "titleHi": "संकटमोचन हनुमानाष्टक",
      "titleEn": "Sankatmochan Hanuman Ashtak",
      "introHi": "यहाँ पढ़ें संकटमोचन हनुमानाष्टक हिंदी अर्थ सहित। भगवान हनुमान की कृपा प्राप्त करने के लिए इसका पाठ करें।",
      "introEn": "Read Sankatmochan Hanuman Ashtak with Hindi meaning. Chant to seek the divine blessings of Lord Hanuman."
    },
    "shiva-mahimna-stotram": {
      "titleHi": "शिवमहिम्नः स्तोत्रम्",
      "titleEn": "Shiva Mahimna Stotram",
      "introHi": "यहाँ पढ़ें शिवमहिम्नः स्तोत्रम् हिंदी अर्थ सहित। भगवान शिव की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shiva Mahimna Stotram with Hindi meaning. Chant this sacred hymn to seek the divine blessings of Lord Shiva."
    },
    "shiva-tandava-stotram": {
      "titleHi": "शिव ताण्डव स्तोत्रम्",
      "titleEn": "Shiva Tandava Stotram",
      "introHi": "यहाँ पढ़ें शिव ताण्डव स्तोत्रम् हिंदी अर्थ सहित। भगवान शिव की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shiva Tandava Stotram with Hindi meaning. Chant this powerful hymn to receive the blessings of Lord Shiva."
    },
    "shri-argala-stotram": {
      "titleHi": "श्री अर्गला स्तोत्रम्",
      "titleEn": "Shri Argala Stotram",
      "introHi": "यहाँ पढ़ें श्री अर्गला स्तोत्रम् हिंदी अर्थ सहित। माँ दुर्गा की भक्ति और कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Argala Stotram with Hindi meaning. Chant this essential hymn to seek the blessings of Maa Durga."
    },
    "shri-bilvashtakam": {
      "titleHi": "श्री बिल्वाष्टकम्",
      "titleEn": "Shri Bilvashtakam",
      "introHi": "यहाँ पढ़ें श्री बिल्वाष्टकम् हिंदी अर्थ सहित। भगवान शिव की भक्ति और कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Bilvashtakam with Hindi meaning. Chant this sacred hymn to seek the blessings of Lord Shiva."
    },
    "shri-devi-kavacham": {
      "titleHi": "श्री देवी कवचम्",
      "titleEn": "Shri Devi Kavacham",
      "introHi": "यहाँ पढ़ें श्री देवी कवचम् हिंदी अर्थ सहित। माँ दुर्गा की सुरक्षा और कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Devi Kavacham with Hindi meaning. Chant this sacred hymn to seek the protection and blessings of Maa Durga."
    },
    "shri-durga-saptashloki": {
      "titleHi": "श्री दुर्गा सप्तश्लोकी",
      "titleEn": "Shri Durga Saptashloki",
      "introHi": "यहाँ पढ़ें श्री दुर्गा सप्तश्लोकी हिंदी अर्थ सहित। माँ दुर्गा की स्तुति और कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Durga Saptashloki with Hindi meaning. Chant these sacred verses to seek the blessings of Maa Durga."
    },
    "shri-kaal-bhairav-ashtakam": {
      "titleHi": "श्री कालभैरवाष्टकम्",
      "titleEn": "Shri Kaal Bhairav Ashtakam",
      "introHi": "यहाँ पढ़ें श्री कालभैरवाष्टकम् हिंदी अर्थ सहित। भगवान कालभैरव की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Kaal Bhairav Ashtakam with Hindi meaning. Chant this sacred hymn to seek the blessings of Lord Kaal Bhairav."
    },
    "shri-lingashtakam": {
      "titleHi": "श्री लिङ्गाष्टकम्",
      "titleEn": "Shri Lingashtakam",
      "introHi": "यहाँ पढ़ें श्री लिङ्गाष्टकम् हिंदी अर्थ सहित। भगवान शिव के शिवलिंग स्वरूप की स्तुति के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Lingashtakam with Hindi meaning. Chant this hymn to praise the Linga form of Lord Shiva."
    },
    "shri-nirvana-shatakam": {
      "titleHi": "श्री निर्वाण षटकम्",
      "titleEn": "Shri Nirvana Shatakam",
      "introHi": "यहाँ पढ़ें श्री निर्वाण षटकम् हिंदी अर्थ सहित। आत्म-ज्ञान और भगवान शिव की स्तुति के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Nirvana Shatakam with Hindi meaning. Chant this profound hymn to seek self-realization and the grace of Lord Shiva."
    },
    "shri-rudrashtakam": {
      "titleHi": "श्री रुद्राष्टकम्",
      "titleEn": "Shri Rudrashtakam",
      "introHi": "यहाँ पढ़ें श्री रुद्राष्टकम् हिंदी अर्थ सहित। भगवान शिव की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इसका पाठ करें।",
      "introEn": "Read Shri Rudrashtakam with Hindi meaning. Chant this sacred hymn to seek the blessings of Lord Shiva."
    },
    "vishnu-sahasranama-stotram": {
      "titleHi": "श्री विष्णु सहस्रनाम स्तोत्रम्",
      "titleEn": "Shri Vishnu Sahasranama Stotram",
      "introHi": "यहाँ पढ़ें श्री विष्णु सहस्रनाम स्तोत्रम् हिंदी अर्थ सहित। भगवान विष्णु की कृपा प्राप्त करने के लिए इसका पाठ करें।",
      "introEn": "Read Shri Vishnu Sahasranama Stotram with Hindi meaning. Chant to receive the divine blessings of Lord Vishnu."
    }
  },
  "Ashtakams": {
    "achyutashtakam": {
      "titleHi": "अच्युताष्टकम्",
      "titleEn": "Achyutashtakam",
      "introHi": "अच्युताष्टकम् भगवान विष्णु (अच्युत) के गुणों और नामों का स्मरण करने वाला अत्यंत भक्तिपूर्ण स्तोत्र है।",
      "introEn": "Achyutashtakam is a devotional hymn dedicated to Lord Vishnu (Achyuta), praising His divine attributes and names."
    },
    "annapurna-ashtakam": {
      "titleHi": "अन्नपूर्णा अष्टकम",
      "titleEn": "Annapurna Ashtakam",
      "introHi": "अन्नपूर्णा अष्टकम आदि शंकराचार्य द्वारा रचित माता अन्नपूर्णा का अत्यंत पवित्र स्तोत्र है। यहाँ पढ़ें इसके संपूर्ण लिरिक्स हिंदी और अंग्रेजी में, साथ ही इसके अर्थ व लाभ।",
      "introEn": "Read Annapurna Ashtakam lyrics in Hindi and English with meaning. Discover the spiritual benefits of chanting this sacred stotram by Adi Shankaracharya for abundance and prosperity."
    },
    "bhavani-ashtakam": {
      "titleHi": "भवानी अष्टकम्",
      "titleEn": "Bhavani Ashtakam",
      "introHi": "भवानी अष्टकम् माता भवानी की स्तुति में रचित पवित्र स्तोत्र है। यहाँ भवानी अष्टकम् का पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Bhavani Ashtakam is a sacred hymn dedicated to Goddess Bhavani. Read the complete Bhavani Ashtakam lyrics, meaning, and benefits."
    },
    "bilvashtakam": {
      "titleHi": "बिल्वाष्टकम्",
      "titleEn": "Bilvashtakam",
      "introHi": "बिल्वाष्टकम् भगवान शिव को प्रिय बिल्व पत्र की महिमा का वर्णन करने वाला स्तोत्र है। यहाँ पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Bilvashtakam is a sacred hymn describing the importance of Bilva leaves offered to Lord Shiva. Read lyrics, meaning, and benefits."
    },
    "brahma-ashtakam": {
      "titleHi": "श्री ब्रह्मा अष्टकम्",
      "titleEn": "Brahma Ashtakam",
      "introHi": "ब्रह्मा जी हिंदू धर्म में सृष्टि के रचयिता माने जाते हैं, जो त्रिदेवों में प्रथम स्थान रखते हैं।",
      "introEn": "Lord Brahma is revered as the creator of the universe in Hindu mythology, occupying the first position in the Trimurti."
    },
    "durga-ashtakam": {
      "titleHi": "दुर्गा अष्टकम्",
      "titleEn": "Durga Ashtakam",
      "introHi": "दुर्गा अष्टकम् माता दुर्गा के शक्ति स्वरूप की वंदना और शत्रुओं तथा भयों के नाश के लिए स्तोत्र है।",
      "introEn": "Durga Ashtakam is a hymn dedicated to Goddess Durga, invoking Her fierce and protective divine energy to overcome fears and adversaries."
    },
    "ganesha-ashtakam": {
      "titleHi": "गणेश अष्टकम्",
      "titleEn": "Ganesha Ashtakam",
      "introHi": "गणेश अष्टकम् विघ्नहर्ता भगवान गणेश की स्तुति और उनके आशीर्वाद प्राप्ति के लिए पढ़ा जाता है।",
      "introEn": "Ganesha Ashtakam is a prayer dedicated to Lord Ganesha, the remover of obstacles, to seek His blessings and protection."
    },
    "ganga-ashtakam": {
      "titleHi": "गङ्गाष्टकम्",
      "titleEn": "Ganga Ashtakam",
      "introHi": "गङ्गाष्टकम् माँ गंगा की महिमा और पवित्रता का वर्णन करने वाला स्तोत्र है। यहाँ इसका पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Ganga Ashtakam is a sacred hymn praising Goddess Ganga. Read the complete lyrics, meaning, and benefits of Ganga Ashtakam."
    },
    "jagannathashtakam": {
      "titleHi": "जगन्नाथाष्टकम्",
      "titleEn": "Jagannathashtakam",
      "introHi": "जगन्नाथाष्टकम् भगवान जगन्नाथ की भक्ति और महिमा का प्रसिद्ध स्तोत्र है। यहाँ इसका पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Jagannathashtakam is a famous hymn dedicated to Lord Jagannath. Read the complete lyrics, meaning, and benefits."
    },
    "krishna-ashtakam": {
      "titleHi": "कृष्णाष्टकम्",
      "titleEn": "Krishna Ashtakam",
      "introHi": "कृष्णाष्टकम् भगवान श्रीकृष्ण के बाल स्वरूप और दिव्य लीलाओं का वर्णन करने वाला लोकप्रिय स्तोत्र है।",
      "introEn": "Krishna Ashtakam is a popular hymn describing the divine childhood and enchanting pastimes of Lord Krishna."
    },
    "lalita-ashtakam": {
      "titleHi": "ललिता अष्टकम्",
      "titleEn": "Lalita Ashtakam",
      "introHi": "ललिता अष्टकम् देवी ललिता त्रिपुरसुन्दरी की स्तुति का पवित्र स्तोत्र है। यहाँ पाठ, अर्थ और लाभ प्राप्त करें।",
      "introEn": "Lalita Ashtakam is a devotional hymn dedicated to Goddess Lalita Tripura Sundari. Read its lyrics, meaning, and benefits."
    },
    "madhurashtakam": {
      "titleHi": "मधुराष्टकम्",
      "titleEn": "Madhurashtakam",
      "introHi": "मधूराष्टकम् श्री कृष्ण के मधुर स्वरूप और उनकी लीलाओं का गुणगान करने वाला महाप्रभु वल्लभाचार्य द्वारा रचित स्तोत्र है।",
      "introEn": "Madhurashtakam is a devotional composition by Sri Vallabhacharya celebrating the sweet and enchanting form and pastimes of Lord Krishna."
    },
    "mahalakshmi-ashtakam": {
      "titleHi": "महालक्ष्मी अष्टकम्",
      "titleEn": "Mahalakshmi Ashtakam",
      "introHi": "महालक्ष्मी अष्टकम् माता लक्ष्मी की कृपा, धन, और समृद्धि प्राप्ति के लिए पाठ किया जाने वाला प्रसिद्ध स्तोत्र है।",
      "introEn": "Mahalakshmi Ashtakam is a powerful prayer chanted to invoke the grace, wealth, and prosperity of Goddess Lakshmi."
    },
    "narasimha-ashtakam": {
      "titleHi": "नरसिंह अष्टकम्",
      "titleEn": "Narasimha Ashtakam",
      "introHi": "नरसिंह अष्टकम् भगवान नरसिंह की महिमा और कृपा का वर्णन करने वाला पवित्र स्तोत्र है। यहाँ पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Narasimha Ashtakam is a powerful hymn dedicated to Lord Narasimha. Read the complete lyrics, meaning, and benefits."
    },
    "rudrashtakam": {
      "titleHi": "रुद्राष्टकम्",
      "titleEn": "Rudrashtakam",
      "introHi": "रुद्राष्टकम् भगवान शिव की महिमा का प्रसिद्ध स्तोत्र है। यहाँ रुद्राष्टकम् का पाठ, अर्थ और आध्यात्मिक लाभ जानें।",
      "introEn": "Rudrashtakam is a powerful hymn dedicated to Lord Shiva. Read the lyrics, meaning, and spiritual benefits of Rudrashtakam."
    },
    "saraswati-ashtakam": {
      "titleHi": "सरस्वती अष्टकम्",
      "titleEn": "Saraswati Ashtakam",
      "introHi": "सरस्वती अष्टकम् माँ सरस्वती की स्तुति का पवित्र स्तोत्र है। यहाँ सरस्वती अष्टकम् का पाठ, अर्थ और लाभ पढ़ें।",
      "introEn": "Saraswati Ashtakam is a sacred hymn dedicated to Goddess Saraswati. Read the complete lyrics, meaning, and benefits."
    },
    "shankarashtakam": {
      "titleHi": "श्री शङ्कराष्टकम्",
      "titleEn": "Shankarashtakam",
      "introHi": "शंकर भगवान शिव का एक प्रमुख और कल्याणकारी रूप हैं, जो योग और संहार के देवता हैं।",
      "introEn": "Lord Shankara is a prominent and benevolent form of Lord Shiva, known as the deity of yoga, transformation, and dissolution."
    },
    "shiva-ashtakam": {
      "titleHi": "शिवाष्टकम्",
      "titleEn": "Shiva Ashtakam",
      "introHi": "शिवाष्टकम् महादेव भगवान शिव की महिमा, करुणा और उनके दिव्य स्वरूप की वंदना करता है।",
      "introEn": "Shiva Ashtakam is a hymn dedicated to Lord Shiva, glorifying His supreme greatness, compassion, and divine form."
    },
    "surya-ashtakam": {
      "titleHi": "श्री सूर्याष्टकम्",
      "titleEn": "Shri Surya Ashtakam",
      "introHi": "सूर्य देव को समर्पित 'सूर्याष्टकम्' एक अत्यंत शक्तिशाली और ऊर्जावान स्तोत्र है। इसके पाठ से आरोग्यता, तेज, और मानसिक शक्ति की प्राप्ति होती है, विशेषकर सूर्योदय के समय इसका पाठ करना अत्यंत फलदायी माना गया है।",
      "introEn": "Shri Surya Ashtakam is a powerful and vibrant eight-verse hymn dedicated to Lord Surya (The Sun God). Regular recitation of this stotram is believed to bestow good health, vitality, clarity of mind, and divine radiance, especially when chanted during sunrise."
    }
  },
  "Sahasranamas": {
    "devi-sahasranama": {
      "titleHi": "देवी सहस्रनाम",
      "titleEn": "Devi Sahasranama",
      "introHi": "देवी सहस्रनाम देवी माता के 1000 नामों की एक पवित्र रचना है जो उनकी अनंत शक्ति और ब्रह्मांडीय प्रकटीकरण का जश्न मनाती है।",
      "introEn": "A sacred composition of 1000 names of the Divine Mother, celebrating her infinite power and cosmic manifestations."
    },
    "durga-sahasranamam": {
      "titleHi": "दुर्गा सहस्रनाम",
      "titleEn": "Durga Sahasranamam",
      "introHi": "दुर्गा सहस्रनाम माता दुर्गा के 1000 पवित्र नामों का स्तोत्र है। इसका श्रद्धापूर्वक पाठ करने से साहस, सुरक्षा और देवी दुर्गा की कृपा प्राप्त होती है।",
      "introEn": "Durga Sahasranamam is the sacred hymn of the 1000 names of Goddess Durga. Chanting it with devotion brings courage, protection, and divine grace."
    },
    "ganesha-sahasranamam": {
      "titleHi": "गणेश सहस्रनाम",
      "titleEn": "Ganesha Sahasranamam",
      "introHi": "गणेश सहस्रनाम भगवान गणेश के 1000 पवित्र नामों का स्तोत्र है। इसका नियमित पाठ करने से विघ्न दूर होते हैं और सुख-समृद्धि की प्राप्ति होती है।",
      "introEn": "Ganesha Sahasranamam is the sacred collection of the 1000 names of Lord Ganesha. Reciting it helps remove obstacles and invites prosperity and wisdom."
    },
    "gayatri-sahasranamam": {
      "titleHi": "गायत्री सहस्रनाम",
      "titleEn": "Gayatri Sahasranamam",
      "introHi": "गायत्री सहस्रनाम माता गायत्री के 1000 पवित्र नामों का स्तोत्र है। इसका पाठ ज्ञान, बुद्धि, आध्यात्मिक उन्नति और देवी गायत्री की कृपा प्राप्त करने के लिए किया जाता है।",
      "introEn": "Gayatri Sahasranamam is the sacred hymn of the 1000 names of Goddess Gayatri. Reciting it brings wisdom, spiritual growth, and divine blessings."
    },
    "hanuman-sahasranamam": {
      "titleHi": "हनुमान सहस्रनाम",
      "titleEn": "Hanuman Sahasranamam",
      "introHi": "हनुमान सहस्रनाम श्री हनुमान जी के 1000 दिव्य नामों का स्तोत्र है। इसका पाठ शक्ति, साहस, भय से मुक्ति और बजरंगबली की कृपा प्राप्त करने के लिए किया जाता है।",
      "introEn": "Hanuman Sahasranamam is the sacred hymn of the 1000 names of Lord Hanuman. Devotees recite it for strength, courage, protection, and divine blessings."
    },
    "krishna-sahasranamam": {
      "titleHi": "कृष्ण सहस्रनाम",
      "titleEn": "Krishna Sahasranamam",
      "introHi": "कृष्ण सहस्रनाम भगवान श्रीकृष्ण के 1000 पवित्र नामों का स्तोत्र है। इसका पाठ भक्ति, प्रेम, शांति और भगवान श्रीकृष्ण की कृपा प्राप्त करने के लिए किया जाता है।",
      "introEn": "Krishna Sahasranamam is the sacred hymn of the 1000 names of Lord Krishna. Chanting it deepens devotion, inner peace, and divine love."
    },
    "lakshmi-sahasranamam": {
      "titleHi": "लक्ष्मी सहस्रनाम",
      "titleEn": "Lakshmi Sahasranamam",
      "introHi": "लक्ष्मी सहस्रनाम माता महालक्ष्मी के 1000 दिव्य नामों का स्तोत्र है। इसका पाठ धन, समृद्धि, सौभाग्य और देवी लक्ष्मी की कृपा प्राप्त करने के लिए किया जाता है।",
      "introEn": "Lakshmi Sahasranamam is the sacred hymn of the 1000 names of Goddess Lakshmi. Devotees chant it to seek wealth, prosperity, good fortune, and divine blessings."
    },
    "narasimha-sahasranamam": {
      "titleHi": "नृसिंह सहस्रनाम",
      "titleEn": "Narasimha Sahasranamam",
      "introHi": "नृसिंह सहस्रनाम भगवान नृसिंह के 1000 दिव्य नामों का स्तोत्र है। इसका पाठ भय, नकारात्मकता और बाधाओं से रक्षा के लिए अत्यंत शुभ माना जाता है।",
      "introEn": "Narasimha Sahasranamam is the sacred hymn of the 1000 names of Lord Narasimha. Devotees chant it for protection, courage, and freedom from fear and negativity."
    },
    "shiva-sahasranamam": {
      "titleHi": "शिव सहस्रनाम",
      "titleEn": "Shiva Sahasranamam",
      "introHi": "शिव सहस्रनाम भगवान शिव के 1000 दिव्य नामों का पवित्र स्तोत्र है। इसका श्रद्धापूर्वक पाठ करने से मन को शांति, आध्यात्मिक शक्ति और भगवान शिव की कृपा प्राप्त होती है।",
      "introEn": "Shiva Sahasranamam is the sacred hymn of the 1000 divine names of Lord Shiva. Chanting it with devotion brings peace, spiritual strength, and the blessings of Mahadev."
    },
    "vishnu-sahasranama": {
      "titleHi": "विष्णु सहस्रनाम",
      "titleEn": "Vishnu Sahasranama",
      "introHi": "विष्णु सहस्रनाम भगवान विष्णु के 1000 नामों की एक पवित्र रचना है, जिसका पाठ सुरक्षा और आध्यात्मिक उन्नति के लिए किया जाता है।",
      "introEn": "A sacred composition of 1000 names of Lord Vishnu, the preserver and sustainer of the universe, recited for protection and spiritual elevation."
    }
  },
  "VratKathas": {
    "ahoi-ashtami-vrat-katha": {
      "titleHi": "श्री अहोई अष्टमी व्रत कथा",
      "titleEn": "Shri Ahoi Ashtami Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री अहोई अष्टमी व्रत कथा हिंदी में। संतान की सुख-समृद्धि, दीर्घायु और मंगलमय जीवन के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Ahoi Ashtami Vrat Katha in English and pray for the well-being, longevity, and happiness of your children."
    },
    "ekadashi-vrat-katha": {
      "titleHi": "श्री एकादशी व्रत कथा",
      "titleEn": "Shri Ekadashi Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री एकादशी व्रत कथा हिंदी में। भगवान विष्णु की कृपा, पापों से मुक्ति और मोक्ष की प्राप्ति के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Ekadashi Vrat Katha in English and seek the blessings of Lord Vishnu for spiritual growth, liberation, and divine grace."
    },
    "ganesh-chaturthi-vrat-katha": {
      "titleHi": "गणेश चतुर्थी व्रत कथा",
      "titleEn": "Ganesh Chaturthi Vrat Katha",
      "introHi": "यहाँ पढ़ें गणेश चतुर्थी व्रत कथा हिंदी में। भगवान गणेश की इस पावन कथा के श्रवण से विघ्न दूर होते हैं और जीवन में सुख, बुद्धि एवं सफलता का आशीर्वाद मिलता है।",
      "introEn": "Read Ganesh Chaturthi Vrat Katha in English and Hindi. This sacred story of Lord Ganesha highlights His divine powers and blessings. Listening to this katha is believed to remove obstacles and bring wisdom, happiness, and success."
    },
    "ganga-dussehra-vrat-katha": {
      "titleHi": "गंगा दशहरा व्रत कथा",
      "titleEn": "Ganga Dussehra Vrat Katha",
      "introHi": "यहाँ पढ़ें गंगा दशहरा व्रत कथा हिंदी में। मां गंगा के पृथ्वी पर अवतरण और राजा भगीरथ की तपस्या से जुड़ी इस पवित्र कथा का श्रवण करने से पुण्य और आध्यात्मिक शांति प्राप्त होती है।",
      "introEn": "Read Ganga Dussehra Vrat Katha in English and Hindi. This sacred story describes the divine descent of Goddess Ganga and King Bhagiratha’s devotion. Listening to this katha is believed to bring purity, peace, and spiritual blessings."
    },
    "guruvar-vrat-katha": {
      "titleHi": "श्री गुरुवार व्रत कथा",
      "titleEn": "Shri Guruvar Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री गुरुवार व्रत कथा हिंदी में। भगवान विष्णु और देवगुरु बृहस्पति की कृपा प्राप्त करने के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Guruvar Vrat Katha in English and seek the blessings of Lord Vishnu and Brihaspati Dev for prosperity and good fortune."
    },
    "hartalika-teej-vrat-katha": {
      "titleHi": "हरतालिका तीज व्रत कथा",
      "titleEn": "Hartalika Teej Vrat Katha",
      "introHi": "यहाँ पढ़ें हरतालिका तीज व्रत कथा हिंदी में। माता पार्वती की कठोर तपस्या और भगवान शिव को पति रूप में प्राप्त करने की यह पावन कथा वैवाहिक सुख और सौभाग्य का महत्व बताती है।",
      "introEn": "Read Hartalika Teej Vrat Katha in English and Hindi. This sacred story of Goddess Parvati’s devotion and penance describes the importance of faith, marital happiness, and the blessings of Lord Shiva and Goddess Parvati."
    },
    "karva-chauth-vrat-katha": {
      "titleHi": "करवा चौथ व्रत कथा",
      "titleEn": "Karva Chauth Vrat Katha",
      "introHi": "करवा चौथ की पवित्र कथा, एक शुभ व्रत जो विवाहित महिलाएं अपने पतियों की दीर्घायु और कल्याण के लिए मनाती हैं।",
      "introEn": "The sacred story of Karva Chauth, an auspicious fast observed by married women for the longevity and well-being of their husbands."
    },
    "karwa-chauth-vrat-katha": {
      "titleHi": "श्री करवा चौथ व्रत कथा",
      "titleEn": "Shri Karwa Chauth Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री करवा चौथ व्रत कथा हिंदी में। अखंड सौभाग्य और पति की दीर्घायु के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Karwa Chauth Vrat Katha in English and pray for marital bliss, good fortune, and your husband’s long life."
    },
    "maha-shivratri-vrat-katha": {
      "titleHi": "महाशिवरात्रि व्रत कथा",
      "titleEn": "Maha Shivratri Vrat Katha",
      "introHi": "यहाँ पढ़ें महाशिवरात्रि व्रत कथा हिंदी में। भगवान शिव की महिमा और भक्तों की श्रद्धा से जुड़ी इस पावन कथा का श्रवण करने से शिव जी की कृपा प्राप्त होती है।",
      "introEn": "Read Maha Shivratri Vrat Katha in English and Hindi. This sacred story describes the glory of Lord Shiva and the power of devotion. Listening to this katha is believed to bring the blessings of Mahadev."
    },
    "navratri-vrat-katha": {
      "titleHi": "नवरात्रि व्रत कथा",
      "titleEn": "Navratri Vrat Katha",
      "introHi": "यहाँ पढ़ें नवरात्रि व्रत कथा हिंदी में। मां दुर्गा के नौ स्वरूपों की महिमा और भक्तों पर उनकी कृपा से जुड़ी इस पवित्र कथा का पाठ करने से शक्ति और सुख-समृद्धि प्राप्त होती है।",
      "introEn": "Read Navratri Vrat Katha in English and Hindi. This sacred story describes the glory of Goddess Durga and her nine divine forms. Listening to this katha is believed to bring strength, peace, prosperity, and divine blessings."
    },
    "pradosh-vrat-katha": {
      "titleHi": "श्री प्रदोष व्रत कथा",
      "titleEn": "Shri Pradosh Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री प्रदोष व्रत कथा हिंदी में। भगवान शिव की कृपा, सुख-समृद्धि और सभी कष्टों के निवारण के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Pradosh Vrat Katha in English and seek the divine blessings of Lord Shiva for peace, prosperity, and relief from difficulties."
    },
    "sakat-chauth-vrat-katha": {
      "titleHi": "सकट चौथ व्रत कथा",
      "titleEn": "Sakat Chauth Vrat Katha",
      "introHi": "यहाँ पढ़ें सकट चौथ व्रत कथा हिंदी में। भगवान गणेश को समर्पित इस पावन व्रत की कथा बच्चों की लंबी आयु, सुख-समृद्धि और परिवार की खुशहाली के लिए सुनी जाती है।",
      "introEn": "Read Sakat Chauth Vrat Katha in English and Hindi. This sacred story dedicated to Lord Ganesha is observed for the well-being, long life, and happiness of children and family prosperity."
    },
    "sankashti-chaturthi-vrat-katha": {
      "titleHi": "श्री संकष्टी चतुर्थी व्रत कथा",
      "titleEn": "Shri Sankashti Chaturthi Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री संकष्टी चतुर्थी व्रत कथा हिंदी में। भगवान गणेश की कृपा और सभी विघ्नों के निवारण के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Sankashti Chaturthi Vrat Katha in English and seek the blessings of Lord Ganesha for the removal of obstacles and success."
    },
    "santoshi-mata-vrat-katha-vidhi": {
      "titleHi": "श्री संतोषी माता व्रत कथा",
      "titleEn": "Shri Santoshi Mata Vrat Katha",
      "introHi": "संतोषी माता की व्रत कथा पढ़ना अत्यंत पुण्यदायी और कल्याणकारी माना जाता है। यहाँ पढ़ें संतोषी माता की संपूर्ण पौराणिक कथा, जिसे सुनकर और सुनाकर भक्तों की सभी मनोकामनाएं पूर्ण होती हैं। भक्ति भाव से इस पवित्र कथा का पाठ करें और माता का आशीर्वाद प्राप्त करें।",
      "introEn": "Discover the complete Santoshi Mata Vrat Katha. Reading or listening to the sacred story of Santoshi Mata is believed to bring peace, prosperity, and the fulfillment of heartfelt desires. Read the authentic narrative here to invoke the blessings of the Mother Goddess."
    },
    "satyanarayan-vrat-katha": {
      "titleHi": "श्री सत्यनारायण व्रत कथा",
      "titleEn": "Shri Satyanarayan Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री सत्यनारायण व्रत कथा हिंदी में। भगवान विष्णु की कृपा, सुख-शांति और समृद्धि प्राप्त करने के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Satyanarayan Vrat Katha in English and receive the divine blessings of Lord Vishnu for peace, prosperity, and success."
    },
    "sawan-vrat-katha": {
      "titleHi": "सावन व्रत कथा",
      "titleEn": "Sawan Vrat Katha",
      "introHi": "यहाँ पढ़ें सावन व्रत कथा हिंदी में। भगवान शिव को समर्पित सावन मास के इस पावन व्रत की कथा का श्रवण करने से भक्तों को महादेव की कृपा, सुख-शांति और मनोकामनाओं की पूर्ति का आशीर्वाद प्राप्त होता है।",
      "introEn": "Read Sawan Vrat Katha in English and Hindi. This sacred story dedicated to Lord Shiva during the holy month of Sawan is believed to bring the blessings of Mahadev, peace, prosperity, and fulfillment of devotees’ wishes."
    },
    "shanivar-vrat-katha": {
      "titleHi": "शनिवार व्रत कथा",
      "titleEn": "Shanivar Vrat Katha",
      "introHi": "यहाँ पढ़ें शनिवार व्रत कथा हिंदी में। भगवान शनि देव की महिमा और उनके न्याय से जुड़ी इस पावन कथा का श्रवण करने से जीवन के कष्ट दूर होते हैं और शनि देव की कृपा प्राप्त होती है।",
      "introEn": "Read Shanivar Vrat Katha in English and Hindi. This sacred story describes the glory of Lord Shani Dev and His divine justice. Listening to this katha is believed to remove difficulties and bring the blessings of Shani Dev."
    },
    "solah-somvar-vrat-katha": {
      "titleHi": "श्री सोलह सोमवार व्रत कथा",
      "titleEn": "Solah somvar vrat katha",
      "introHi": "यहाँ पढ़ें श्री सोलह सोमवार व्रत कथा हिंदी में। भगवान शिव की कृपा और मनोकामना पूर्ति के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Solah Somvar Vrat Katha in English and seek the divine blessings of Lord Shiva for wish fulfillment and spiritual growth."
    },
    "teej-vrat-katha": {
      "titleHi": "तीज व्रत कथा",
      "titleEn": "Teej Vrat Katha",
      "introHi": "तीज की पवित्र कथा, एक आनंदमय त्योहार जो महिलाएं विवाह सुख, संतानोत्पत्ति और पारिवारिक खुशियों के लिए मनाती हैं।",
      "introEn": "The sacred story of Teej, a joyous festival celebrated by women for marital bliss, fertility, and family happiness."
    },
    "vaibhav-lakshmi-vrat-katha": {
      "titleHi": "श्री वैभव लक्ष्मी व्रत कथा",
      "titleEn": "Shri Vaibhav Lakshmi Vrat Katha",
      "introHi": "यहाँ पढ़ें श्री वैभव लक्ष्मी व्रत कथा हिंदी में। माता लक्ष्मी की कृपा, धन-वैभव और सुख-समृद्धि के लिए श्रद्धापूर्वक इस कथा का पाठ करें।",
      "introEn": "Read Shri Vaibhav Lakshmi Vrat Katha in English and seek the blessings of Goddess Lakshmi for wealth, prosperity, and happiness."
    }
  },
  "Temples": {
    "badrinath-temple": {
      "titleHi": "श्री बद्रीनाथ मंदिर उत्तराखंड",
      "titleEn": "Shri Badrinath Temple, Uttarakhand",
      "introHi": "श्री बद्रीनाथ मंदिर उत्तराखंड के चमोली जिले में स्थित भगवान विष्णु को समर्पित भारत के सबसे पवित्र और प्रसिद्ध तीर्थ स्थलों में से एक है। यह मंदिर चार धाम यात्रा और छोटा चार धाम यात्रा का प्रमुख हिस्सा है।",
      "introEn": "The Shri Badrinath Temple, located in the Chamoli district of Uttarakhand, is one of the holiest and most famous pilgrimage sites in India dedicated to Lord Vishnu."
    },
    "banke-bihari-temple-vrindavan": {
      "titleHi": "श्री बांके बिहारी मंदिर वृंदावन, उत्तर प्रदेश",
      "titleEn": "Shri Banke Bihari Temple, Vrindavan",
      "introHi": "श्री बांके बिहारी मंदिर उत्तर प्रदेश के पवित्र शहर वृंदावन में स्थित भगवान श्री कृष्ण को समर्पित भारत के सबसे प्रसिद्ध कृष्ण मंदिरों में से एक है।",
      "introEn": "The Shri Banke Bihari Temple is one of the holiest and most visited temples in Vrindavan, dedicated to Lord Krishna. The idol here was discovered by Swami Haridas, a legendary devotee and musician."
    },
    "chintpurni-temple": {
      "titleHi": "श्री चिंतपूर्णी मंदिर",
      "titleEn": "Shri Chintpurni Temple, Himachal Pradesh",
      "introHi": "श्री चिंतपूर्णी मंदिर हिमाचल प्रदेश के ऊना जिले में स्थित भारत के प्रसिद्ध शक्तिपीठों में से एक है। यह मंदिर माता चिंतपूर्णी देवी को समर्पित है और लाखों श्रद्धालुओं की आस्था का प्रमुख केंद्र है।",
      "introEn": "Shri Chintpurni Temple, located in the Una district of Himachal Pradesh, is an extremely holy Shakti Peeth. The temple is dedicated to Mata Chhinnamastika Devi."
    },
    "dwarkadhish-temple-dwarka": {
      "titleHi": "श्री द्वारकाधीश मंदिर द्वारका, गुजरात",
      "titleEn": "Shri Dwarkadhish Temple, Dwarka",
      "introHi": "श्री द्वारकाधीश मंदिर, जिसे जगत मंदिर के नाम से भी जाना जाता है, गुजरात के द्वारका शहर में स्थित है। यह मंदिर भगवान श्रीकृष्ण को समर्पित है और हिंदुओं की पवित्र 'चार धाम' यात्रा का एक अत्यंत महत्वपूर्ण हिस्सा है।",
      "introEn": "The Shri Dwarkadhish Temple, also known as the Jagat Mandir, is located in the city of Dwarka, Gujarat. This temple is dedicated to Lord Shri Krishna and is a vital part of the sacred 'Char Dham' pilgrimage in Hinduism."
    },
    "iskcon-krishna-balaram-temple": {
      "titleHi": "श्री श्री कृष्ण बलराम मंदिर वृंदावन, उत्तर प्रदेश",
      "titleEn": "ISKCON Krishna Balaram Temple, Vrindavan",
      "introHi": "श्री श्री कृष्ण बलराम मंदिर (ISKCON Krishna Balaram Temple) – वृंदावन, उत्तर प्रदेश",
      "introEn": "The ISKCON Krishna Balaram Temple in Vrindavan is one of the most beautiful and spiritually uplifting temples in India. It is a major center for the International Society for Krishna Consciousness (ISKCON)."
    },
    "jagannath-temple-puri": {
      "titleHi": "श्री जगन्नाथ मंदिर पुरी, ओडिशा",
      "titleEn": "Shri Jagannath Temple, Puri",
      "introHi": "श्री जगन्नाथ मंदिर ओडिशा के पुरी शहर में स्थित भगवान जगन्नाथ को समर्पित भारत के सबसे प्रसिद्ध और पवित्र मंदिरों में से एक है।",
      "introEn": "The Shri Jagannath Temple, located in the city of Puri, Odisha, is one of the most famous and sacred temples in India dedicated to Lord Jagannath."
    },
    "jwala-ji-temple": {
      "titleHi": "श्री ज्वाला जी मंदिर हिमाचल प्रदेश",
      "titleEn": "Shri Jwala Ji Temple, Himachal Pradesh",
      "introHi": "श्री ज्वाला जी मंदिर हिमाचल प्रदेश के कांगड़ा जिले में स्थित भारत के प्रसिद्ध शक्तिपीठों में से एक है। यह मंदिर माता ज्वाला देवी को समर्पित है और अपनी अनंत प्राकृतिक ज्वालाओं (पवित्र ज्योतियों) के लिए विश्व प्रसिद्ध है।",
      "introEn": "The Shri Jwala Ji Temple, located in the Kangra district of Himachal Pradesh, is one of the famous Shakti Peethas of India."
    },
    "kamakhya-temple-guwahati": {
      "titleHi": "श्री कामाख्या मंदिर गुवाहाटी",
      "titleEn": "Shri Kamakhya Temple, Guwahati",
      "introHi": "श्री कामाख्या मंदिर असम के गुवाहाटी शहर में नीलाचल पहाड़ी पर स्थित भारत के सबसे प्रसिद्ध शक्तिपीठों में से एक है।",
      "introEn": "श्री कामाख्या मंदिर भारत के सबसे पुराने और सबसे पवित्र शक्तिपीठों में से एक है। यह असम के गुवाहाटी में नीलाचल पहाड़ी पर स्थित है। यह मंदिर देवी कामाख्या को समर्पित है और तांत्रिक साधना का एक प्रमुख केंद्र माना जाता है। यहाँ कोई मूर्ति नहीं है, बल्कि देवी की 'योनि' के रूप में पूजा की जाती है।"
    },
    "kashi-vishwanath-temple-varanasi": {
      "titleHi": "श्री काशी विश्वनाथ मंदिर वाराणसी",
      "titleEn": "Shri Kashi Vishwanath Temple, Varanasi",
      "introHi": "श्री काशी विश्वनाथ मंदिर वाराणसी, उत्तर प्रदेश में स्थित भगवान शिव को समर्पित भारत के सबसे पवित्र और प्रसिद्ध मंदिरों में से एक है।",
      "introEn": "The Shri Kashi Vishwanath Temple in Varanasi, Uttar Pradesh, is one of the most sacred and famous temples in India dedicated to Lord Shiva."
    },
    "kedarnath-temple": {
      "titleHi": "श्री केदारनाथ मंदिर – उत्तराखंड",
      "titleEn": "Shri Kedarnath Temple, Uttarakhand",
      "introHi": "श्री केदारनाथ मंदिर उत्तराखंड के रुद्रप्रयाग जिले में स्थित भगवान शिव को समर्पित भारत के सबसे पवित्र मंदिरों में से एक है।",
      "introEn": "The Shri Kedarnath Temple, situated in the Rudraprayag district of Uttarakhand, is one of the most sacred temples in India dedicated to Lord Shiva."
    },
    "khatu-shyam-ji-temple": {
      "titleHi": "श्री खाटू श्याम जी मंदिर राजस्थान",
      "titleEn": "Shri Khatu Shyam Ji Temple, Rajasthan",
      "introHi": "श्री खाटू श्याम जी मंदिर राजस्थान के सीकर जिले के खाटू गांव में स्थित भारत के सबसे प्रसिद्ध कृष्ण भक्त मंदिरों में से एक है।",
      "introEn": "The Khatu Shyam Ji Temple, located in the Sikar district of Rajasthan, is one of the most prominent pilgrimage sites in India."
    },
    "mahakaleshwar-jyotirlinga-ujjain": {
      "titleHi": "श्री महाकालेश्वर ज्योतिर्लिंग मंदिर उज्जैन, मध्य प्रदेश",
      "titleEn": "Shri Mahakaleshwar Jyotirlinga Temple, Ujjain (MP)",
      "introHi": "हाकालेश्वर ज्योतिर्लिंग मंदिर (Shri Mahakaleshwar Jyotirlinga Temple) – उज्जैन, मध्य प्रदेश",
      "introEn": "The Shri Mahakaleshwar Jyotirlinga Temple, located in the city of Ujjain, Madhya Pradesh, is one of the most famous and sacred temples in India dedicated to Lord Shiva."
    },
    "meenakshi-amman-temple-madurai": {
      "titleHi": "श्री मीनाक्षी अम्मन मंदिर मदुरै, तमिलनाडु",
      "titleEn": "Shri Meenakshi Amman Temple, Madurai",
      "introHi": "श्री मीनाक्षी अम्मन मंदिर तमिलनाडु के मदुरै शहर में स्थित भारत के सबसे प्रसिद्ध और प्राचीन मंदिरों में से एक है। यह मंदिर देवी मीनाक्षी (माता पार्वती का स्वरूप) और भगवान सुंदरेश्वर (भगवान शिव) को समर्पित है।",
      "introEn": "Shri Meenakshi Amman Temple, located in the city of Madurai, Tamil Nadu, is one of the most famous and ancient temples in India."
    },
    "mehandipur-balaji-temple": {
      "titleHi": "श्री मेहंदीपुर बालाजी मंदिर राजस्थान",
      "titleEn": "Shri Mehandipur Balaji Temple",
      "introHi": "श्री मेहंदीपुर बालाजी मंदिर राजस्थान के दौसा जिले में स्थित भगवान हनुमान जी के प्रसिद्ध मंदिरों में से एक है।",
      "introEn": "The Mehandipur Balaji Temple is one of the most prominent pilgrimage centers in Rajasthan. Dedicated to Lord Hanuman, this temple is revered not only for the deity’s presence but also for its unique spiritual atmosphere."
    },
    "naina-devi-temple": {
      "titleHi": "श्री नैना देवी मंदिर हिमाचल प्रदेश",
      "titleEn": "Shri Naina Devi Temple, Himachal Pradesh",
      "introHi": "श्री नैना देवी मंदिर हिमाचल प्रदेश के बिलासपुर जिले में स्थित भारत के प्रसिद्ध शक्तिपीठों में से एक है। यह मंदिर माता नैना देवी को समर्पित है और लाखों श्रद्धालुओं की आस्था का प्रमुख केंद्र है।",
      "introEn": "Shri Naina Devi Temple, located in the Bilaspur district of Himachal Pradesh, is one of the most sacred Shakti Peethas in India. This temple is dedicated to the 'eyes' (Naina) of Mother Sati."
    },
    "omkareshwar-jyotirlinga-temple": {
      "titleHi": "श्री ओंकारेश्वर ज्योतिर्लिंग मंदिर मध्य प्रदेश",
      "titleEn": "Shri Omkareshwar Jyotirlinga Temple",
      "introHi": "श्री ओंकारेश्वर ज्योतिर्लिंग मंदिर (Shri Omkareshwar Jyotirlinga Temple) – मध्य प्रदेश",
      "introEn": "The Shri Omkareshwar Jyotirlinga Temple, located on the holy banks of the Narmada River in the Khandwa district of Madhya Pradesh, is a famous pilgrimage site dedicated to Lord Shiva."
    },
    "prem-mandir-vrindavan": {
      "titleHi": "श्री प्रेम मंदिर वृंदावन, उत्तर प्रदेश",
      "titleEn": "Shri Prem Mandir, Vrindavan",
      "introHi": "श्री प्रेम मंदिर उत्तर प्रदेश के पवित्र धाम वृंदावन में स्थित एक भव्य और प्रसिद्ध मंदिर है। यह मंदिर भगवान राधा-कृष्ण और सीता-राम को समर्पित है।",
      "introEn": "Prem Mandir, located in Vrindavan, is a breathtaking temple dedicated to the divine love of Shri Radha-Krishna and Shri Sita-Ram."
    },
    "ram-janmabhoomi-mandir-ayodhya": {
      "titleHi": "श्री राम जन्मभूमि मंदिर अयोध्या",
      "titleEn": "Shri Ram Janmabhoomi Mandir, Ayodhya",
      "introHi": "श्री राम जन्मभूमि मंदिर अयोध्या, उत्तर प्रदेश में स्थित भगवान श्री राम को समर्पित एक भव्य और पवित्र मंदिर है। यह स्थान भगवान श्री राम की जन्मभूमि के रूप में हिंदू धर्म में अत्यंत श्रद्धा और आस्था का केंद्र माना जाता है।",
      "introEn": "The Shri Ram Janmabhoomi Mandir in Ayodhya, Uttar Pradesh, is a grand and sacred temple dedicated to Lord Shri Ram."
    },
    "ramanathaswamy-temple-rameswaram": {
      "titleHi": "श्री रामनाथस्वामी मंदिर रामेश्वरम, तमिलनाडु",
      "titleEn": "Shri Ramanathaswamy Temple, Rameswaram",
      "introHi": "श्री रामनाथस्वामी मंदिर तमिलनाडु के रामेश्वरम द्वीप पर स्थित भगवान शिव को समर्पित भारत के सबसे पवित्र मंदिरों में से एक है। यह मंदिर भगवान शिव के 12 ज्योतिर्लिंगों में से एक है और हिंदू धर्म के चार धामों में भी शामिल है।",
      "introEn": "Shri Ramanathaswamy Temple, located on Rameswaram Island in Tamil Nadu, is one of the holiest temples in India dedicated to Lord Shiva."
    },
    "salasar-balaji-temple": {
      "titleHi": "श्री सालासर बालाजी मंदिर",
      "titleEn": "Shri Salasar Balaji Temple",
      "introHi": "श्री सालासर बालाजी मंदिर राजस्थान के चूरू जिले के सालासर कस्बे में स्थित भगवान हनुमान जी को समर्पित भारत के प्रसिद्ध हनुमान मंदिरों में से एक है। इसे सालासर धाम के नाम से भी जाना जाता है।",
      "introEn": "The Salasar Balaji Temple is one of the most significant pilgrimage sites for devotees of Lord Hanuman in India."
    },
    "shirdi-sai-baba-temple": {
      "titleHi": "श्री शिरडी साईं बाबा मंदिर महाराष्ट्र",
      "titleEn": "Shri Shirdi Sai Baba Temple",
      "introHi": "श्री शिरडी साईं बाबा मंदिर महाराष्ट्र के शिरडी शहर में स्थित भारत के सबसे प्रसिद्ध आध्यात्मिक तीर्थ स्थलों में से एक है। यह मंदिर महान संत श्री साईं बाबा को समर्पित है।",
      "introEn": "Shirdi, the home of the revered saint Sai Baba, is one of the most significant spiritual destinations in India."
    },
    "siddhivinayak-temple-mumbai": {
      "titleHi": "श्री सिद्धिविनायक मंदिर मुंबई",
      "titleEn": "Shri Siddhivinayak Temple, Mumbai",
      "introHi": "श्री सिद्धिविनायक मंदिर महाराष्ट्र के मुंबई शहर में स्थित भगवान गणेश को समर्पित भारत के सबसे प्रसिद्ध गणपति मंदिरों में से एक है। यह मंदिर विशेष रूप से भक्तों की गहरी आस्था और भगवान गणेश के आशीर्वाद के लिए प्रसिद्ध है।",
      "introEn": "Shri Siddhivinayak Temple, located in Prabhadevi, Mumbai, is a highly prestigious and popular temple dedicated to Lord Ganesha."
    },
    "somnath-temple": {
      "titleHi": "श्री सोमनाथ मंदिर गुजरात",
      "titleEn": "Shri Somnath Temple, Gujarat",
      "introHi": "श्री सोमनाथ मंदिर गुजरात के गिर सोमनाथ जिले में स्थित भगवान शिव को समर्पित भारत के सबसे प्राचीन और पवित्र मंदिरों में से एक है। यह मंदिर भगवान शिव के 12 ज्योतिर्लिंगों में प्रथम ज्योतिर्लिंग के रूप में प्रसिद्ध है।",
      "introEn": "The Shri Somnath Temple, located in the Gir Somnath district of Gujarat, is one of the most ancient and sacred temples in India dedicated to Lord Shiva. It is famous as the first of the 12 Jyotirlingas of Lord Shiva."
    },
    "tirumala-venkateswara-temple-tirupati": {
      "titleHi": "श्री तिरुमला वेंकटेश्वर मंदिर तिरुपति बालाजी",
      "titleEn": "Tirumala Venkateswara Temple, Tirupati",
      "introHi": "श्री तिरुमला वेंकटेश्वर मंदिर जिसे तिरुपति बालाजी मंदिर के नाम से भी जाना जाता है, आंध्र प्रदेश के तिरुमला पर्वत पर स्थित भगवान विष्णु को समर्पित भारत के सबसे प्रसिद्ध और समृद्ध मंदिरों में से एक है।",
      "introEn": "The Sri Tirumala Venkateswara Temple, also known as the Tirupati Balaji Temple, is one of the most famous and prosperous temples in India."
    },
    "vaishno-devi-temple-katra": {
      "titleHi": "श्री माता वैष्णो देवी मंदिर कटरा",
      "titleEn": "Shri Mata Vaishno Devi Temple, Katra (J&K)",
      "introHi": "श्री माता वैष्णो देवी मंदिर (Shri Mata Vaishno Devi Temple) – कटरा जम्मू और कश्मीर",
      "introEn": "The Shri Mata Vaishno Devi Temple is one of the most famous and sacred Shaktipeeths (power centers) and a major religious pilgrimage site in India."
    }
  },
  "Festivals": {
    "baisakhi": {
      "titleHi": "बैसाखी",
      "titleEn": "Baisakhi",
      "introHi": "बैसाखी भारत का एक प्रमुख कृषि और धार्मिक पर्व है, जो मुख्य रूप से पंजाब, हरियाणा और उत्तर भारत में बड़े उत्साह के साथ मनाया जाता है।",
      "introEn": "Baisakhi is one of the most important harvest and religious festivals of Punjab and North India."
    },
    "chhath-puja": {
      "titleHi": "छठ पूजा",
      "titleEn": "Chhath Puja",
      "introHi": "छठ पूजा हिंदू धर्म का एक अत्यंत पवित्र और प्रसिद्ध सूर्य उपासना पर्व है, जो मुख्य रूप से बिहार, झारखंड, उत्तर प्रदेश और नेपाल के कुछ क्षेत्रों में बड़े श्रद्धा और उत्साह के साथ मनाया जाता है।",
      "introEn": "Chhath Puja is one of the most sacred and ancient Hindu festivals dedicated to Surya Dev (Sun God) and Chhathi Maiya."
    },
    "diwali": {
      "titleHi": "दीपावली (दिवाली)",
      "titleEn": "Diwali (Deepavali) – Festival of Lights",
      "introHi": "दीपावली (Diwali), जिसे दीपों का त्योहार और Festival of Lights कहा जाता है, भारत का सबसे प्रसिद्ध हिंदू त्योहार है।",
      "introEn": "Diwali, also known as Deepavali and the Festival of Lights, is one of the most celebrated Hindu festivals in India and around the world."
    },
    "durga-puja": {
      "titleHi": "दुर्गा पूजा",
      "titleEn": "Durga Puja",
      "introHi": "दुर्गा पूजा हिंदू धर्म का एक अत्यंत पवित्र और भव्य पर्व है, जो मुख्य रूप से पश्चिम बंगाल, असम, ओडिशा, त्रिपुरा और देश के कई अन्य क्षेत्रों में बड़े उत्साह के साथ मनाया जाता है।",
      "introEn": "Durga Puja is one of the most important and grand Hindu festivals celebrated mainly in West Bengal, Assam, Odisha, Tripura, and many other parts of India."
    },
    "dussehra": {
      "titleHi": "दशहरा (विजयादशमी)",
      "titleEn": "Dussehra (Vijayadashami)",
      "introHi": "दशहरा, जिसे विजयादशमी भी कहा जाता है, हिंदू धर्म का एक प्रमुख और पवित्र पर्व है। यह आश्विन मास के शुक्ल पक्ष की दशमी तिथि को मनाया जाता है, जो सामान्यतः सितंबर या अक्टूबर महीने में पड़ती है।",
      "introEn": "Dussehra, also known as Vijayadashami, is one of the most important and widely celebrated Hindu festivals."
    },
    "ganesh-chaturthi": {
      "titleHi": "श्री गणेश चतुर्थी",
      "titleEn": "Ganesh Chaturthi",
      "introHi": "श्री गणेश चतुर्थी हिंदू धर्म का एक प्रमुख और अत्यंत शुभ पर्व है, जो भगवान श्रीगणेश के जन्मोत्सव के रूप में मनाया जाता है।",
      "introEn": "Ganesh Chaturthi is one of the most sacred and widely celebrated Hindu festivals, observed as the birth anniversary of Lord Ganesha, the remover of obstacles and the God of wisdom, prosperity, and new beginnings."
    },
    "gudi-padwa": {
      "titleHi": "गुड़ी पड़वा",
      "titleEn": "Gudi Padwa",
      "introHi": "गुड़ी पड़वा महाराष्ट्र और गोवा का एक प्रमुख हिंदू पर्व है, जिसे मराठी नववर्ष के रूप में मनाया जाता है।",
      "introEn": "Gudi Padwa is a major Hindu festival celebrated mainly in Maharashtra and Goa as the Marathi New Year."
    },
    "hanuman-jayanti": {
      "titleHi": "हनुमान जयंती",
      "titleEn": "Hanuman Jayanti",
      "introHi": "हनुमान जयंती हिंदू धर्म का एक प्रमुख और पवित्र पर्व है, जो भगवान हनुमान जी के जन्मोत्सव के रूप में मनाया जाता है।",
      "introEn": "Hanuman Jayanti is one of the most important and sacred Hindu festivals celebrated to commemorate the birth of Lord Hanuman, the divine devotee of Lord Rama."
    },
    "holi": {
      "titleHi": "होली",
      "titleEn": "Holi – Festival of Colors",
      "introHi": "होली भारत के सबसे लोकप्रिय हिंदू त्योहारों में से एक है, जिसे रंगों का त्योहार भी कहा जाता है।",
      "introEn": "Holi, also known as the Festival of Colors, is one of the most popular Hindu festivals celebrated across India and many parts of the world."
    },
    "janmashtami": {
      "titleHi": "श्रीकृष्ण जन्माष्टमी",
      "titleEn": "Shri Krishna Janmashtami",
      "introHi": "श्रीकृष्ण जन्माष्टमी हिंदू धर्म का एक प्रमुख और पवित्र त्योहार है, जो भगवान श्रीकृष्ण के जन्मोत्सव के रूप में मनाया जाता है।",
      "introEn": "Shri Krishna Janmashtami is one of the most sacred and widely celebrated Hindu festivals, observed as the birth anniversary of Lord Krishna, the eighth incarnation of Lord Vishnu."
    },
    "kali-puja": {
      "titleHi": "काली पूजा",
      "titleEn": "Kali puja",
      "introHi": "काली पूजा पश्चिम बंगाल, असम, ओडिशा और पूर्वी भारत का एक प्रमुख हिंदू पर्व है, जो माँ काली को समर्पित है।",
      "introEn": "Kali Puja is one of the most important Hindu festivals celebrated mainly in West Bengal, Assam, Odisha, and other parts of Eastern India."
    },
    "karthigai-deepam": {
      "titleHi": "कार्तिगई दीपम",
      "titleEn": "Karthigai Deepam",
      "introHi": "कार्तिगई दीपम तमिलनाडु का एक प्रमुख और पवित्र हिंदू पर्व है, जो भगवान शिव और भगवान मुरुगन (कार्तिकेय) को समर्पित है।",
      "introEn": "Karthigai Deepam is one of the most sacred Hindu festivals celebrated mainly in Tamil Nadu."
    },
    "karva-chauth": {
      "titleHi": "करवा चौथ",
      "titleEn": "Karva Chauth",
      "introHi": "करवा चौथ हिंदू धर्म का एक प्रमुख और पवित्र व्रत एवं त्योहार है, जिसे विवाहित महिलाएँ अपने पति की लंबी आयु, उत्तम स्वास्थ्य और सुखी वैवाहिक जीवन की कामना के लिए रखती हैं।",
      "introEn": "Karva Chauth is one of the most sacred Hindu festivals observed primarily by married women for the long life, good health, and well-being of their husbands."
    },
    "lakshmi-puja": {
      "titleHi": "लक्ष्मी पूजा",
      "titleEn": "Lakshmi Puja",
      "introHi": "लक्ष्मी पूजा हिंदू धर्म का एक प्रमुख और पवित्र पर्व है, जो माँ लक्ष्मी, धन, समृद्धि, सौभाग्य और सुख-शांति की देवी को समर्पित है।",
      "introEn": "Lakshmi Puja is one of the most sacred Hindu festivals dedicated to Goddess Lakshmi, the deity of wealth, prosperity, fortune, and happiness."
    },
    "lohri": {
      "titleHi": "लोहड़ी",
      "titleEn": "Lohri",
      "introHi": "लोहड़ी उत्तर भारत का एक प्रसिद्ध हिंदू और सांस्कृतिक पर्व है, जिसे मुख्य रूप से पंजाब, हरियाणा और उत्तर भारत के अन्य क्षेत्रों में बड़े उत्साह के साथ मनाया जाता है।",
      "introEn": "Lohri is a popular Hindu and cultural festival celebrated mainly in Punjab, Haryana, and northern parts of India."
    },
    "maha-shivratri": {
      "titleHi": "महाशिवरात्रि",
      "titleEn": "Maha Shivratri",
      "introHi": "महाशिवरात्रि हिंदू धर्म का एक अत्यंत पवित्र और महत्वपूर्ण पर्व है, जो भगवान शिव की आराधना और उपासना के लिए समर्पित है।",
      "introEn": "Maha Shivratri is one of the most sacred and significant Hindu festivals dedicated to Lord Shiva."
    },
    "makar-sankranti": {
      "titleHi": "मकर संक्रांति",
      "titleEn": "Makar Sankranti",
      "introHi": "मकर संक्रांति हिंदू धर्म का एक प्रमुख और पवित्र पर्व है, जो सूर्य देव के मकर राशि में प्रवेश करने के उपलक्ष्य में मनाया जाता है।",
      "introEn": "Makar Sankranti is one of the most important Hindu festivals, celebrated to mark the Sun’s transition into Makara (Capricorn) and the beginning of Uttarayana, the Sun’s northward journey."
    },
    "navratri": {
      "titleHi": "शारदीय नवरात्रि",
      "titleEn": "Sharadiya Navratri",
      "introHi": "शारदीय नवरात्रि हिंदू धर्म का एक प्रमुख और अत्यंत पवित्र पर्व है, जो माँ दुर्गा के नौ स्वरूपों की आराधना के लिए समर्पित है।",
      "introEn": "Sharadiya Navratri is one of the most sacred and widely celebrated Hindu festivals dedicated to the worship of the nine divine forms of Goddess Durga."
    },
    "onam": {
      "titleHi": "ओणम",
      "titleEn": "Onam",
      "introHi": "ओणम केरल का सबसे प्रमुख और भव्य हिंदू पर्व है, जो नई फसल, समृद्धि, संस्कृति और राजा महाबली की स्मृति में मनाया जाता है।",
      "introEn": ""
    },
    "pongal": {
      "titleHi": "पोंगल",
      "titleEn": "Pongal",
      "introHi": "पोंगल दक्षिण भारत, विशेष रूप से तमिलनाडु का सबसे प्रमुख और पवित्र हिंदू पर्व है। यह चार दिनों तक मनाया जाने वाला फसल उत्सव है, जो सूर्य देव, प्रकृति, वर्षा और पशुधन के प्रति कृतज्ञता व्यक्त करने का प्रतीक है।",
      "introEn": "Pongal is one of the most important and widely celebrated Hindu harvest festivals, primarily observed in the Indian state of Tamil Nadu."
    },
    "raksha-bandhan": {
      "titleHi": "रक्षाबंधन",
      "titleEn": "Raksha Bandhan",
      "introHi": "रक्षाबंधन हिंदू धर्म का एक प्रमुख और पावन पर्व है, जो भाई-बहन के अटूट प्रेम, विश्वास और स्नेह का प्रतीक माना जाता है।",
      "introEn": "Raksha Bandhan is one of the most cherished Hindu festivals, celebrating the sacred bond of love, trust, and protection between brothers and sisters."
    },
    "ram-navami": {
      "titleHi": "श्री राम नवमी",
      "titleEn": "Shri Ram Navami",
      "introHi": "श्री राम नवमी हिंदू धर्म का एक अत्यंत पवित्र और महत्वपूर्ण पर्व है, जो भगवान श्रीराम के जन्मोत्सव के रूप में मनाया जाता है।",
      "introEn": "Shri Ram Navami is one of the most sacred and significant Hindu festivals, celebrated as the birth anniversary of Lord Rama, the seventh incarnation of Lord Vishnu."
    },
    "ratha-yatra": {
      "titleHi": "रथ यात्रा",
      "titleEn": "Ratha Yatra (Jagannath Rath Yatra)",
      "introHi": "रथ यात्रा हिंदू धर्म का एक अत्यंत पवित्र और प्रसिद्ध पर्व है, जो मुख्य रूप से ओडिशा के पुरी स्थित भगवान जगन्नाथ मंदिर में भव्य रूप से मनाया जाता है।",
      "introEn": "Ratha Yatra, also known as Jagannath Rath Yatra, is one of the most sacred and famous Hindu festivals celebrated mainly in Puri, Odisha."
    },
    "rongali-bihu": {
      "titleHi": "रंगाली बिहू (बोहाग बिहू)",
      "titleEn": "Rongali Bihu (Bohag Bihu)",
      "introHi": "रंगाली बिहू, जिसे बोहाग बिहू भी कहा जाता है, असम का सबसे प्रमुख और लोकप्रिय त्योहार है। यह पर्व असमिया नववर्ष और नई फसल के आगमन का प्रतीक माना जाता है।",
      "introEn": "Rongali Bihu, also known as Bohag Bihu, is the most important and widely celebrated festival of Assam."
    },
    "saraswati-puja": {
      "titleHi": "सरस्वती पूजा",
      "titleEn": "Saraswati Puja",
      "introHi": "सरस्वती पूजा हिंदू धर्म का एक प्रमुख पर्व है, जो माँ सरस्वती, ज्ञान, संगीत, कला, विद्या और बुद्धि की देवी को समर्पित है।",
      "introEn": "Saraswati Puja is a sacred Hindu festival dedicated to Goddess Saraswati, the goddess of knowledge, wisdom, music, art, learning, and speech."
    },
    "thaipusam": {
      "titleHi": "थाईपुसम",
      "titleEn": "Thaipusam",
      "introHi": "थाईपुसम दक्षिण भारत, विशेष रूप से तमिल समुदाय का एक प्रमुख हिंदू पर्व है, जो भगवान मुरुगन (कार्तिकेय) को समर्पित है।",
      "introEn": "Thaipusam is a major Hindu festival celebrated by the Tamil community, especially in Tamil Nadu and by Tamil people around the world."
    },
    "ugadi": {
      "titleHi": "उगादि",
      "titleEn": "Ugadi",
      "introHi": "उगादि दक्षिण भारत का एक प्रमुख हिंदू पर्व है, जिसे आंध्र प्रदेश, तेलंगाना और कर्नाटक में हिंदू नववर्ष के रूप में मनाया जाता है।",
      "introEn": "Ugadi, also known as Yugadi, is one of the most important Hindu festivals celebrated as the New Year in the states of Andhra Pradesh, Telangana, and Karnataka."
    },
    "varalakshmi-vratam": {
      "titleHi": "वरलक्ष्मी व्रतम",
      "titleEn": "Varalakshmi Vratam",
      "introHi": "वरलक्ष्मी व्रतम दक्षिण भारत का एक प्रमुख हिंदू व्रत और पर्व है, जो देवी लक्ष्मी के वरलक्ष्मी स्वरूप को समर्पित है।",
      "introEn": "Varalakshmi Vratam is one of the most important Hindu fasting festivals celebrated in South India, especially in Andhra Pradesh, Telangana, Karnataka, and Tamil Nadu."
    },
    "vasant-panchami": {
      "titleHi": "वसंत पंचमी",
      "titleEn": "Vasant Panchami",
      "introHi": "वसंत पंचमी हिंदू धर्म का एक पवित्र और शुभ पर्व है, जो विद्या, ज्ञान, कला, संगीत और वाणी की अधिष्ठात्री देवी माँ सरस्वती को समर्पित है।",
      "introEn": "Vasant Panchami is a sacred Hindu festival dedicated to Goddess Saraswati, the goddess of wisdom, knowledge, learning, music, arts, and speech."
    },
    "vishu": {
      "titleHi": "विषु",
      "titleEn": "Vishu",
      "introHi": "विषु केरल का एक प्रमुख और पवित्र हिंदू पर्व है, जिसे मलयालम नववर्ष और समृद्धि के प्रतीक के रूप में मनाया जाता है।",
      "introEn": "Vishu is one of the most important Hindu festivals celebrated in the Indian state of Kerala."
    }
  }
};
